import type { Theme, Subject } from './types'
import { roundToYear } from './utils'

function t(
  partial: Omit<Theme, 'examYears' | 'count' | 'latestRound'>
): Theme {
  return {
    ...partial,
    examYears: partial.examRounds.map(roundToYear),
    count: partial.examRounds.length,
    latestRound: Math.max(...partial.examRounds),
  }
}

export const subjects: Subject[] = [
  { id: 'medical-overview',   name: '医療概論',             shortName: '医療概論',   description: '医療の基本概念・医の倫理・チーム医療・インフォームドコンセント' },
  { id: 'hygiene',            name: '衛生学・公衆衛生学',   shortName: '衛生',       description: '健康増進・感染症・生活習慣病・環境保健・統計' },
  { id: 'regulations',        name: '関係法規',             shortName: '法規',       description: 'あはき法・医療法・介護保険法など業務に関する法令' },
  { id: 'anatomy',            name: '解剖学',               shortName: '解剖',       description: '人体の構造（骨格・筋・神経・循環器・消化器など）' },
  { id: 'physiology',         name: '生理学',               shortName: '生理',       description: '人体の機能（神経・循環・呼吸・消化・内分泌など）' },
  { id: 'pathology',          name: '病理学概論',           shortName: '病理',       description: '疾患の成り立ち（炎症・腫瘍・変性・壊死・再生）' },
  { id: 'clinical-general',   name: '臨床医学総論',         shortName: '臨床総論',   description: '診断学・治療学・感染・免疫・代謝など総論的な医学知識' },
  { id: 'clinical-specific',  name: '臨床医学各論',         shortName: '臨床各論',   description: '各臓器・系統の疾患（循環・呼吸・消化・神経・整形など）' },
  { id: 'rehabilitation',     name: 'リハビリテーション医学', shortName: 'リハ',     description: '障害の概念・リハビリの手法・ADL・装具・義肢など' },
  { id: 'oriental-overview',  name: '東洋医学概論',         shortName: '東洋概論',   description: '陰陽五行・気血津液・蔵象・病因病機・弁証など基礎理論' },
  { id: 'meridians-acupoints',name: '経絡経穴概論',         shortName: '経絡経穴',   description: '十二経脈・奇経八脈・経穴の部位と特定穴など' },
  { id: 'acupuncture-theory', name: 'はり理論',             shortName: 'はり',       description: '刺鍼法・補瀉・刺激量・リスク管理など' },
  { id: 'moxibustion-theory', name: 'きゅう理論',           shortName: 'きゅう',     description: '施灸法の種類・刺激量・禁灸・リスク管理など' },
  { id: 'oriental-clinical',  name: '東洋医学臨床論',       shortName: '東洋臨床',   description: '弁証論治・経絡病証・各科疾患の東洋医学的対応など' },
]

export const themes: Theme[] = [
  // ── 経絡経穴概論 ──────────────────────────────
  t({
    id: 'gen-ketsu',
    name: '原穴',
    subject: 'meridians-acupoints',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '経穴',
    officialMedium: '特定穴',
    officialSmall: '原穴',
    normalizedTheme: '特定穴',
    aliases: ['十二原穴'],
    relatedThemes: ['geki-ketsu', 'bo-ketsu', 'go-yu-ketsu', 'kei-ketsu-shuchi'],
    studyPoint: '各経脈の原穴12穴を完全暗記。陰経の原穴＝五兪穴の輸穴と一致。原気が集まる部位で臓腑の診断・治療に重要。臓腑の疾患に対して広く用いる。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'geki-ketsu',
    name: '郄穴',
    subject: 'meridians-acupoints',
    examRounds: [29, 30, 31, 32, 33],
    importance: 'A',
    officialLarge: '経穴',
    officialMedium: '特定穴',
    officialSmall: '郄穴',
    normalizedTheme: '特定穴',
    aliases: [],
    relatedThemes: ['gen-ketsu', 'go-yu-ketsu'],
    studyPoint: '十六郄穴（十二経＋陰維・陽維・陰蹻・陽蹻の郄穴）を表で整理。急性疾患・疼痛に用いる。陰の郄穴は血証に、陽の郄穴は気証に有効。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'bo-ketsu',
    name: '募穴',
    subject: 'meridians-acupoints',
    examRounds: [29, 30, 31, 32, 34],
    importance: 'A',
    officialLarge: '経穴',
    officialMedium: '特定穴',
    officialSmall: '募穴',
    normalizedTheme: '特定穴',
    aliases: ['腹募穴'],
    relatedThemes: ['gen-ketsu', 'go-yu-ketsu', 'kei-ketsu-shuchi'],
    studyPoint: '12臓腑の募穴を暗記。腹部・胸部に位置し診断と治療に用いる。背部兪穴との対比（俞募配穴）が頻出。各募穴の帰属経脈との関係も確認。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'go-yu-ketsu',
    name: '五兪穴',
    subject: 'meridians-acupoints',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '経穴',
    officialMedium: '特定穴',
    officialSmall: '五要穴（五兪穴）',
    normalizedTheme: '特定穴',
    aliases: ['五要穴', '五腧穴'],
    relatedThemes: ['gen-ketsu', 'geki-ketsu', 'bo-ketsu'],
    studyPoint: '井・榮・輸・経・合の5種類と五行配当（陰経：木火土金水、陽経：金水木火土）を完全習得。「病が変わる所は」の原文と各穴の適応も頻出。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'kiki-hachi-myaku',
    name: '奇経八脈',
    subject: 'meridians-acupoints',
    examRounds: [29, 30, 32, 33, 34],
    importance: 'A',
    officialLarge: '経絡',
    officialMedium: '奇経',
    officialSmall: '奇経八脈の種類・走行・機能',
    normalizedTheme: '奇経',
    aliases: ['奇経'],
    relatedThemes: ['juni-kei-myaku', 'kei-myaku-ryuchu'],
    studyPoint: '督脈・任脈・衝脈・帯脈・陰維脈・陽維脈・陰蹻脈・陽蹻脈の8脈の走行と機能を整理。督脈（陽の海）・任脈（陰の海）・衝脈（血の海）の役割と交会穴が頻出。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'juni-kei-myaku',
    name: '十二経脈',
    subject: 'meridians-acupoints',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '経絡',
    officialMedium: '正経十二経脈',
    officialSmall: '十二経脈の概要と表裏関係',
    normalizedTheme: '正経十二経脈',
    aliases: ['正経十二経脈'],
    relatedThemes: ['kiki-hachi-myaku', 'kei-myaku-ryuchu', 'kei-ketsu-shuchi'],
    studyPoint: '陰陽・表裏関係と流注順序を体系的に理解。手足の陰陽区別（手の三陰三陽・足の三陰三陽）と臓腑の対応が必須。6年連続出題のコア中のコア。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'kei-myaku-ryuchu',
    name: '経脈の流注',
    subject: 'meridians-acupoints',
    examRounds: [29, 30, 31, 32, 34],
    importance: 'A',
    officialLarge: '経絡',
    officialMedium: '正経十二経脈',
    officialSmall: '各経脈の流注・起始・終止',
    normalizedTheme: '正経十二経脈',
    aliases: [],
    relatedThemes: ['juni-kei-myaku', 'kiki-hachi-myaku'],
    studyPoint: '肺経から始まり肝経で終わる流注の順序と各経脈の起始・終止・走行概略を暗記。経穴が帰属する経脈を問う問題が頻出。解剖学的位置と合わせて学習。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'kei-ketsu-shuchi',
    name: '経穴の主治',
    subject: 'meridians-acupoints',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '経穴',
    officialMedium: '経穴の作用と主治',
    officialSmall: '主要経穴の主治症',
    normalizedTheme: '経穴の主治',
    aliases: [],
    relatedThemes: ['juni-kei-myaku', 'gen-ketsu', 'bo-ketsu'],
    studyPoint: '百会・足三里・三陰交・合谷・太衝・内関・委中など主要穴の主治を優先暗記。特定穴の主治パターンを理解すると効率的。6年全回出題の最重要テーマ。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 東洋医学概論 ──────────────────────────────
  t({
    id: 'in-yo-ron',
    name: '陰陽論',
    subject: 'oriental-overview',
    examRounds: [29, 30, 31, 33, 34],
    importance: 'A',
    officialLarge: '東洋医学の基礎理論',
    officialMedium: '陰陽論',
    officialSmall: '陰陽の概念・属性・相互関係',
    normalizedTheme: '陰陽論',
    aliases: [],
    relatedThemes: ['go-gyo-ron', 'ki-ketsu-shin-eki'],
    studyPoint: '対立・互根・消長・転化の4関係を理解。臓腑（陰臓・陽腑）、気血、寒熱、表裏への応用が頻出。「陰中の陽」「陽中の陰」の概念と五臓の陰陽分類も押さえる。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'go-gyo-ron',
    name: '五行論',
    subject: 'oriental-overview',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '東洋医学の基礎理論',
    officialMedium: '五行論',
    officialSmall: '五行の相生・相克・相乗・相侮',
    normalizedTheme: '五行論',
    aliases: [],
    relatedThemes: ['in-yo-ron', 'zo-sho'],
    studyPoint: '相生・相克・相乗・相侮の関係と五臓・五腑・五色・五味・五季・五方・五志・五声・五体・五官の対応表を完全暗記。6年連続出題の超頻出テーマ。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ki-ketsu-shin-eki',
    name: '気血津液',
    subject: 'oriental-overview',
    examRounds: [29, 30, 31, 32, 33],
    importance: 'A',
    officialLarge: '生理',
    officialMedium: '気血津液',
    officialSmall: '気血津液の生成・運行・機能・病変',
    normalizedTheme: '気血津液',
    aliases: ['気血水'],
    relatedThemes: ['in-yo-ron', 'zo-sho'],
    studyPoint: '気の種類（元気・宗気・営気・衛気）と機能。血の生成と循行。津液の種類（津・液）と分布。それぞれの病変（気虚・気滞・血虚・血瘀・痰飲など）まで整理。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'zo-sho',
    name: '蔵象',
    subject: 'oriental-overview',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'A',
    officialLarge: '生理',
    officialMedium: '蔵象学説',
    officialSmall: '五臓六腑の機能と相互関係',
    normalizedTheme: '蔵象学説',
    aliases: ['蔵象学説', '五臓六腑'],
    relatedThemes: ['go-gyo-ron', 'ki-ketsu-shin-eki', 'roku-in'],
    studyPoint: '心・肝・脾・肺・腎の機能（「心は血脈を主る」等）と病変を徹底理解。六腑との表裏関係も必須。奇恒の腑の種類と「蔵精気而不瀉」の概念も押さえる。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'roku-in',
    name: '六淫',
    subject: 'oriental-overview',
    examRounds: [29, 30, 31, 33],
    importance: 'B',
    officialLarge: '病因病機',
    officialMedium: '外因',
    officialSmall: '六淫の概念・性質・致病特徴',
    normalizedTheme: '病因論',
    aliases: ['六邪', '六気'],
    relatedThemes: ['shichi-jo', 'zo-sho'],
    studyPoint: '風・寒・暑・湿・燥・火（熱）の性質と侵す臓腑・引き起こす症状を対応表で整理。「風は百病の長」などの格言も出題される。季節との対応も確認。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'shichi-jo',
    name: '七情',
    subject: 'oriental-overview',
    examRounds: [30, 31, 32, 34],
    importance: 'B',
    officialLarge: '病因病機',
    officialMedium: '内因',
    officialSmall: '七情の概念と五臓への影響',
    normalizedTheme: '病因論',
    aliases: [],
    relatedThemes: ['roku-in', 'zo-sho'],
    studyPoint: '喜（心）・怒（肝）・憂（肺）・思（脾）・悲（肺）・恐（腎）・驚（腎）と五臓の対応を暗記。七情が過度になると各臓の気機を乱すことを理解。病因論の内因として整理。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'toyo-rekishi',
    name: '東洋医学の歴史',
    subject: 'oriental-overview',
    examRounds: [29, 31, 33],
    importance: 'C',
    officialLarge: '東洋医学の基礎理論',
    officialMedium: '東洋医学の歴史',
    officialSmall: '主要な医学書と医家',
    normalizedTheme: '東洋医学の歴史',
    aliases: [],
    relatedThemes: ['in-yo-ron', 'go-gyo-ron'],
    studyPoint: '黄帝内経・難経・傷寒論・神農本草経などの成立年代と内容概要を把握。張仲景（傷寒論）・李時珍（本草綱目）など重要医家と著作の対応を整理。日本への伝来も確認。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 衛生学・公衆衛生学 ──────────────────────────
  t({
    id: 'kenko-nihon-21',
    name: '健康日本21',
    subject: 'hygiene',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'A',
    officialLarge: '健康増進',
    officialMedium: '健康づくり対策',
    officialSmall: '健康日本21（各次）の目標と評価',
    normalizedTheme: '健康増進政策',
    aliases: ['健康日本21（第三次）', '健康増進計画'],
    relatedThemes: ['seikatsu-shukan-byo'],
    studyPoint: '健康日本21の各次（第一次〜第三次）の期間・目標を整理。第三次（2024〜2035年）の基本方針を把握。BMI・歩数・飲酒量などの数値目標が出題される。6年連続出題。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'kansen-sho',
    name: '感染症',
    subject: 'hygiene',
    examRounds: [29, 30, 31, 32, 33],
    importance: 'A',
    officialLarge: '感染症',
    officialMedium: '感染症の予防と対策',
    officialSmall: '感染症法による分類・届出・対応',
    normalizedTheme: '感染症対策',
    aliases: ['感染症法', '新興感染症', '再興感染症'],
    relatedThemes: ['seikatsu-shukan-byo', 'menekigaku'],
    studyPoint: '感染症法の1〜5類分類と届出期限を表で整理。主要感染症（結核・コレラ・ペスト等）の病原体・感染経路・潜伏期間を把握。院内感染防止対策・標準予防策も出題。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'seikatsu-shukan-byo',
    name: '生活習慣病',
    subject: 'hygiene',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'A',
    officialLarge: '疾病の予防',
    officialMedium: '生活習慣病',
    officialSmall: 'メタボリックシンドロームと特定健診・特定保健指導',
    normalizedTheme: '生活習慣病対策',
    aliases: ['メタボリックシンドローム', '特定健診'],
    relatedThemes: ['kenko-nihon-21'],
    studyPoint: 'メタボリックシンドロームの診断基準（腹囲・血圧・血糖・脂質の数値）を暗記。特定健診・特定保健指導の対象者・内容・目的を理解。一次・二次・三次予防の概念も整理。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 解剖学 ────────────────────────────────────
  t({
    id: 'kin-kishi-teishi',
    name: '筋の起始停止',
    subject: 'anatomy',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '筋系',
    officialMedium: '全身の骨格筋',
    officialSmall: '各筋の起始・停止・作用・支配神経',
    normalizedTheme: '筋系',
    aliases: [],
    relatedThemes: ['kansetsu-kozo', 'no-shinkei'],
    studyPoint: '上肢（三角筋・上腕二頭筋・大胸筋等）・下肢（大腿四頭筋・腓腹筋・中殿筋等）・体幹（脊柱起立筋等）の起始・停止・作用を解剖図と照合しながら暗記。6年連続出題。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'no-shinkei',
    name: '脳神経',
    subject: 'anatomy',
    examRounds: [29, 30, 31, 32, 34],
    importance: 'A',
    officialLarge: '神経系',
    officialMedium: '末梢神経系',
    officialSmall: '脳神経（12対）の名称・番号・機能分類',
    normalizedTheme: '神経系',
    aliases: ['12脳神経', '脳神経12対'],
    relatedThemes: ['jiritsu-shinkei', 'kin-kishi-teishi'],
    studyPoint: 'Ⅰ嗅〜Ⅻ舌下神経の名称・番号・機能種別（感覚/運動/混合/副交感）を表で暗記。顔面神経（Ⅶ）・迷走神経（Ⅹ）の詳細が特に頻出。出走部位も整理。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'kansetsu-kozo',
    name: '関節の構造',
    subject: 'anatomy',
    examRounds: [29, 30, 31, 33],
    importance: 'B',
    officialLarge: '骨格系',
    officialMedium: '関節',
    officialSmall: '関節の種類・構造・可動性',
    normalizedTheme: '骨格系',
    aliases: [],
    relatedThemes: ['kin-kishi-teishi'],
    studyPoint: '単軸・二軸・多軸関節の種類（蝶番・球・車軸・楕円・鞍・平面関節）と代表的な関節例を整理。靭帯の名称と機能も頻出。肩関節・膝関節の詳細を優先学習。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 生理学 ────────────────────────────────────
  t({
    id: 'jiritsu-shinkei',
    name: '自律神経',
    subject: 'physiology',
    examRounds: [29, 30, 31, 32, 33],
    importance: 'A',
    officialLarge: '神経系の機能',
    officialMedium: '自律神経系',
    officialSmall: '交感神経・副交感神経の作用比較',
    normalizedTheme: '自律神経系',
    aliases: [],
    relatedThemes: ['no-shinkei', 'junkan-kino'],
    studyPoint: '交感神経と副交感神経の各臓器への作用を比較表で整理（瞳孔・心拍・血管・消化・膀胱等）。アドレナリン受容体（α1・α2・β1・β2）の基本も押さえる。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'junkan-kino',
    name: '循環機能',
    subject: 'physiology',
    examRounds: [29, 30, 32, 34],
    importance: 'B',
    officialLarge: '循環機能',
    officialMedium: '心臓の機能と血液循環',
    officialSmall: '心臓の構造・刺激伝導系・体循環と肺循環',
    normalizedTheme: '循環器系',
    aliases: [],
    relatedThemes: ['jiritsu-shinkei'],
    studyPoint: '刺激伝導系（洞房結節→房室結節→ヒス束→左右脚→プルキンエ線維）と体循環・肺循環の流れを暗記。心拍出量・血圧調節（レニン・アンジオテンシン系等）も整理。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 関係法規 ────────────────────────────────────
  t({
    id: 'kanke-hokki',
    name: '関係法規',
    subject: 'regulations',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'A',
    officialLarge: '関係法規',
    officialMedium: 'あん摩マッサージ指圧師、はり師、きゅう師等に関する法律',
    officialSmall: '業務範囲・免許・施術所の管理・広告規制・罰則',
    normalizedTheme: 'あはき法',
    aliases: ['あはき法', 'あん摩法'],
    relatedThemes: [],
    studyPoint: '業務独占と名称独占の区別、免許の要件・欠格事由、業務停止・免許取消の規定を整理。施術所の届出要件と衛生管理基準・広告規制の内容が頻出。6年連続出題。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── はり理論 ────────────────────────────────────
  t({
    id: 'hari-risk-kanri',
    name: '鍼のリスク管理',
    subject: 'acupuncture-theory',
    examRounds: [29, 30, 31, 32, 33],
    importance: 'A',
    officialLarge: 'リスク管理',
    officialMedium: '鍼療法の医療過誤と副作用',
    officialSmall: '折鍼・内出血・神経損傷・気胸・感染の原因と対応',
    normalizedTheme: 'リスク管理',
    aliases: [],
    relatedThemes: ['hari-shigeki-ryo', 'kyu-fukusayo'],
    studyPoint: '折鍼・内出血・神経損傷・気胸・感染それぞれの原因・予防・対応を整理。消毒法（アルコール・オートクレーブ等）の適用場面も出題。禁鍼部位と施術前確認事項も確認。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'hari-shigeki-ryo',
    name: '鍼の刺激量',
    subject: 'acupuncture-theory',
    examRounds: [29, 31, 32, 33],
    importance: 'B',
    officialLarge: '鍼の操作',
    officialMedium: '刺激の調節',
    officialSmall: '刺激量を構成する要素と補瀉法',
    normalizedTheme: '鍼操作',
    aliases: [],
    relatedThemes: ['hari-risk-kanri'],
    studyPoint: '鍼の太さ・長さ・刺入深度・角度・手技（雀啄・旋捻・置鍼等）・留針時間の組み合わせによる刺激量の調節を理解。補瀉の原則（迎随・呼吸・開闔・陰陽補瀉）も整理。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── きゅう理論 ────────────────────────────────────
  t({
    id: 'kyu-fukusayo',
    name: '灸の副作用',
    subject: 'moxibustion-theory',
    examRounds: [29, 31, 32, 33],
    importance: 'B',
    officialLarge: 'リスク管理',
    officialMedium: '灸療法の医療過誤と副作用',
    officialSmall: '施灸による熱傷と禁灸部位',
    normalizedTheme: 'リスク管理',
    aliases: [],
    relatedThemes: ['hari-risk-kanri'],
    studyPoint: '熱傷の深度（Ⅰ度・Ⅱ度・Ⅲ度）の判別と処置を整理。禁灸部位（大血管・目・顔面等）を暗記。無瘢痕灸と有瘢痕灸の特徴と適応。施灸量の調節法も出題。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 東洋医学臨床論 ────────────────────────────────
  t({
    id: 'ben-sho-ron-chi',
    name: '弁証論治',
    subject: 'oriental-clinical',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'A',
    officialLarge: '弁証論治',
    officialMedium: '八綱弁証',
    officialSmall: '陰陽・表裏・寒熱・虚実の弁別と治則',
    normalizedTheme: '弁証論治',
    aliases: ['八綱弁証', '証'],
    relatedThemes: ['kei-myaku-byo-sho', 'in-yo-ron', 'zo-sho'],
    studyPoint: '八綱弁証（陰陽・表裏・寒熱・虚実）が最頻出。各弁証の症候を対比表で整理。臓腑弁証・気血津液弁証・経絡弁証の概要も把握。「証」概念の理解が前提。6年連続出題。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'kei-myaku-byo-sho',
    name: '経絡病証',
    subject: 'oriental-clinical',
    examRounds: [29, 30, 32, 33],
    importance: 'B',
    officialLarge: '弁証論治',
    officialMedium: '経絡弁証',
    officialSmall: '十二経脈の病証（是動病・所生病）',
    normalizedTheme: '弁証論治',
    aliases: ['是動病', '所生病'],
    relatedThemes: ['ben-sho-ron-chi', 'juni-kei-myaku'],
    studyPoint: '霊枢「経脈篇」の是動病・所生病の概念を理解。各経脈の病証の特徴（症状パターン）を経脈ごとに整理。経絡弁証と臓腑弁証の相互関係も押さえる。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 臨床医学総論 ────────────────────────────────
  t({
    id: 'menekigaku',
    name: '免疫学',
    subject: 'clinical-general',
    examRounds: [29, 30, 32, 33],
    importance: 'B',
    officialLarge: '疾患の成立と生体反応',
    officialMedium: '免疫機構',
    officialSmall: '自然免疫・獲得免疫・アレルギー・自己免疫疾患',
    normalizedTheme: '免疫学',
    aliases: [],
    relatedThemes: ['kansen-sho'],
    studyPoint: '自然免疫（NK細胞・マクロファージ等）と獲得免疫（T細胞・B細胞）の役割を整理。アレルギーの分類（Ⅰ〜Ⅳ型）と代表疾患を対応付けて暗記。補体・MHCの概念も確認。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
]

export function getSubject(id: string): Subject | undefined {
  return subjects.find(s => s.id === id)
}

export function getTheme(id: string): Theme | undefined {
  return themes.find(t => t.id === id)
}

export function getThemesBySubject(subjectId: string): Theme[] {
  return themes
    .filter(t => t.subject === subjectId)
    .sort((a, b) => {
      const order = { S: 0, A: 1, B: 2, C: 3 }
      return order[a.importance] - order[b.importance] || b.count - a.count
    })
}
