import type { Theme, Subject } from './types'
import { roundToYear } from './utils'

function t(
  partial: Omit<Theme, 'examYears' | 'count' | 'latestRound'>
): Theme {
  return {
    ...partial,
    examYears: partial.examRounds.map(roundToYear),
    count: partial.examRounds.length,
    latestRound: Math.max(...partial.examRounds),
  }
}

export const subjects: Subject[] = [
  { id: 'medical-overview',   name: '医療概論',             shortName: '医療概論',   description: '医療の基本概念・医の倫理・チーム医療・インフォームドコンセント' },
  { id: 'hygiene',            name: '衛生学・公衆衛生学',   shortName: '衛生',       description: '健康増進・感染症・生活習慣病・環境保健・統計' },
  { id: 'regulations',        name: '関係法規',             shortName: '法規',       description: 'あはき法・医療法・介護保険法など業務に関する法令' },
  { id: 'anatomy',            name: '解剖学',               shortName: '解剖',       description: '人体の構造（骨格・筋・神経・循環器・消化器など）' },
  { id: 'physiology',         name: '生理学',               shortName: '生理',       description: '人体の機能（神経・循環・呼吸・消化・内分泌など）' },
  { id: 'pathology',          name: '病理学概論',           shortName: '病理',       description: '疾患の成り立ち（炎症・腫瘍・変性・壊死・再生）' },
  { id: 'clinical-general',   name: '臨床医学総論',         shortName: '臨床総論',   description: '診断学・治療学・感染・免疫・代謝など総論的な医学知識' },
  { id: 'clinical-specific',  name: '臨床医学各論',         shortName: '臨床各論',   description: '各臓器・系統の疾患（循環・呼吸・消化・神経・整形など）' },
  { id: 'rehabilitation',     name: 'リハビリテーション医学', shortName: 'リハ',     description: '障害の概念・リハビリの手法・ADL・装具・義肢など' },
  { id: 'oriental-overview',  name: '東洋医学概論',         shortName: '東洋概論',   description: '陰陽五行・気血津液・蔵象・病因病機・弁証など基礎理論' },
  { id: 'meridians-acupoints',name: '経絡経穴概論',         shortName: '経絡経穴',   description: '十二経脈・奇経八脈・経穴の部位と特定穴など' },
  { id: 'acupuncture-theory', name: 'はり理論',             shortName: 'はり',       description: '刺鍼法・補瀉・刺激量・リスク管理など' },
  { id: 'moxibustion-theory', name: 'きゅう理論',           shortName: 'きゅう',     description: '施灸法の種類・刺激量・禁灸・リスク管理など' },
  { id: 'oriental-clinical',  name: '東洋医学臨床論',       shortName: '東洋臨床',   description: '弁証論治・経絡病証・各科疾患の東洋医学的対応など' },
]

export const themes: Theme[] = [
  // ── 経絡経穴概論 ──────────────────────────────
  t({
    id: 'gen-ketsu',
    name: '原穴',
    subject: 'meridians-acupoints',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '経穴',
    officialMedium: '特定穴',
    officialSmall: '原穴',
    normalizedTheme: '特定穴',
    aliases: ['十二原穴'],
    relatedThemes: ['geki-ketsu', 'bo-ketsu', 'go-yu-ketsu', 'kei-ketsu-shuchi'],
    studyPoint: '各経脈の原穴12穴を完全暗記。陰経の原穴＝五兪穴の輸穴と一致。原気が集まる部位で臓腑の診断・治療に重要。臓腑の疾患に対して広く用いる。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'geki-ketsu',
    name: '郄穴',
    subject: 'meridians-acupoints',
    examRounds: [29, 30, 31, 32, 33],
    importance: 'A',
    officialLarge: '経穴',
    officialMedium: '特定穴',
    officialSmall: '郄穴',
    normalizedTheme: '特定穴',
    aliases: [],
    relatedThemes: ['gen-ketsu', 'go-yu-ketsu'],
    studyPoint: '十六郄穴（十二経＋陰維・陽維・陰蹻・陽蹻の郄穴）を表で整理。急性疾患・疼痛に用いる。陰の郄穴は血証に、陽の郄穴は気証に有効。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'bo-ketsu',
    name: '募穴',
    subject: 'meridians-acupoints',
    examRounds: [29, 30, 31, 32, 34],
    importance: 'A',
    officialLarge: '経穴',
    officialMedium: '特定穴',
    officialSmall: '募穴',
    normalizedTheme: '特定穴',
    aliases: ['腹募穴'],
    relatedThemes: ['gen-ketsu', 'go-yu-ketsu', 'kei-ketsu-shuchi'],
    studyPoint: '12臓腑の募穴を暗記。腹部・胸部に位置し診断と治療に用いる。背部兪穴との対比（俞募配穴）が頻出。各募穴の帰属経脈との関係も確認。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'go-yu-ketsu',
    name: '五兪穴',
    subject: 'meridians-acupoints',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '経穴',
    officialMedium: '特定穴',
    officialSmall: '五要穴（五兪穴）',
    normalizedTheme: '特定穴',
    aliases: ['五要穴', '五腧穴'],
    relatedThemes: ['gen-ketsu', 'geki-ketsu', 'bo-ketsu'],
    studyPoint: '井・榮・輸・経・合の5種類と五行配当（陰経：木火土金水、陽経：金水木火土）を完全習得。「病が変わる所は」の原文と各穴の適応も頻出。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'kiki-hachi-myaku',
    name: '奇経八脈',
    subject: 'meridians-acupoints',
    examRounds: [29, 30, 32, 33, 34],
    importance: 'A',
    officialLarge: '経絡',
    officialMedium: '奇経',
    officialSmall: '奇経八脈の種類・走行・機能',
    normalizedTheme: '奇経',
    aliases: ['奇経'],
    relatedThemes: ['juni-kei-myaku', 'kei-myaku-ryuchu'],
    studyPoint: '督脈・任脈・衝脈・帯脈・陰維脈・陽維脈・陰蹻脈・陽蹻脈の8脈の走行と機能を整理。督脈（陽の海）・任脈（陰の海）・衝脈（血の海）の役割と交会穴が頻出。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'juni-kei-myaku',
    name: '十二経脈',
    subject: 'meridians-acupoints',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '経絡',
    officialMedium: '正経十二経脈',
    officialSmall: '十二経脈の概要と表裏関係',
    normalizedTheme: '正経十二経脈',
    aliases: ['正経十二経脈'],
    relatedThemes: ['kiki-hachi-myaku', 'kei-myaku-ryuchu', 'kei-ketsu-shuchi'],
    studyPoint: '陰陽・表裏関係と流注順序を体系的に理解。手足の陰陽区別（手の三陰三陽・足の三陰三陽）と臓腑の対応が必須。6年連続出題のコア中のコア。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'kei-myaku-ryuchu',
    name: '経脈の流注',
    subject: 'meridians-acupoints',
    examRounds: [29, 30, 31, 32, 34],
    importance: 'A',
    officialLarge: '経絡',
    officialMedium: '正経十二経脈',
    officialSmall: '各経脈の流注・起始・終止',
    normalizedTheme: '正経十二経脈',
    aliases: [],
    relatedThemes: ['juni-kei-myaku', 'kiki-hachi-myaku'],
    studyPoint: '肺経から始まり肝経で終わる流注の順序と各経脈の起始・終止・走行概略を暗記。経穴が帰属する経脈を問う問題が頻出。解剖学的位置と合わせて学習。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'kei-ketsu-shuchi',
    name: '経穴の主治',
    subject: 'meridians-acupoints',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '経穴',
    officialMedium: '経穴の作用と主治',
    officialSmall: '主要経穴の主治症',
    normalizedTheme: '経穴の主治',
    aliases: [],
    relatedThemes: ['juni-kei-myaku', 'gen-ketsu', 'bo-ketsu'],
    studyPoint: '百会・足三里・三陰交・合谷・太衝・内関・委中など主要穴の主治を優先暗記。特定穴の主治パターンを理解すると効率的。6年全回出題の最重要テーマ。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 東洋医学概論 ──────────────────────────────
  t({
    id: 'in-yo-ron',
    name: '陰陽論',
    subject: 'oriental-overview',
    examRounds: [29, 30, 31, 33, 34],
    importance: 'A',
    officialLarge: '東洋医学の基礎理論',
    officialMedium: '陰陽論',
    officialSmall: '陰陽の概念・属性・相互関係',
    normalizedTheme: '陰陽論',
    aliases: [],
    relatedThemes: ['go-gyo-ron', 'ki-ketsu-shin-eki'],
    studyPoint: '対立・互根・消長・転化の4関係を理解。臓腑（陰臓・陽腑）、気血、寒熱、表裏への応用が頻出。「陰中の陽」「陽中の陰」の概念と五臓の陰陽分類も押さえる。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'go-gyo-ron',
    name: '五行論',
    subject: 'oriental-overview',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '東洋医学の基礎理論',
    officialMedium: '五行論',
    officialSmall: '五行の相生・相克・相乗・相侮',
    normalizedTheme: '五行論',
    aliases: [],
    relatedThemes: ['in-yo-ron', 'zo-sho'],
    studyPoint: '相生・相克・相乗・相侮の関係と五臓・五腑・五色・五味・五季・五方・五志・五声・五体・五官の対応表を完全暗記。6年連続出題の超頻出テーマ。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ki-ketsu-shin-eki',
    name: '気血津液',
    subject: 'oriental-overview',
    examRounds: [29, 30, 31, 32, 33],
    importance: 'A',
    officialLarge: '生理',
    officialMedium: '気血津液',
    officialSmall: '気血津液の生成・運行・機能・病変',
    normalizedTheme: '気血津液',
    aliases: ['気血水'],
    relatedThemes: ['in-yo-ron', 'zo-sho'],
    studyPoint: '気の種類（元気・宗気・営気・衛気）と機能。血の生成と循行。津液の種類（津・液）と分布。それぞれの病変（気虚・気滞・血虚・血瘀・痰飲など）まで整理。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'zo-sho',
    name: '蔵象',
    subject: 'oriental-overview',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'A',
    officialLarge: '生理',
    officialMedium: '蔵象学説',
    officialSmall: '五臓六腑の機能と相互関係',
    normalizedTheme: '蔵象学説',
    aliases: ['蔵象学説', '五臓六腑'],
    relatedThemes: ['go-gyo-ron', 'ki-ketsu-shin-eki', 'roku-in'],
    studyPoint: '心・肝・脾・肺・腎の機能（「心は血脈を主る」等）と病変を徹底理解。六腑との表裏関係も必須。奇恒の腑の種類と「蔵精気而不瀉」の概念も押さえる。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'roku-in',
    name: '六淫',
    subject: 'oriental-overview',
    examRounds: [29, 30, 31, 33],
    importance: 'B',
    officialLarge: '病因病機',
    officialMedium: '外因',
    officialSmall: '六淫の概念・性質・致病特徴',
    normalizedTheme: '病因論',
    aliases: ['六邪', '六気'],
    relatedThemes: ['shichi-jo', 'zo-sho'],
    studyPoint: '風・寒・暑・湿・燥・火（熱）の性質と侵す臓腑・引き起こす症状を対応表で整理。「風は百病の長」などの格言も出題される。季節との対応も確認。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'shichi-jo',
    name: '七情',
    subject: 'oriental-overview',
    examRounds: [30, 31, 32, 34],
    importance: 'B',
    officialLarge: '病因病機',
    officialMedium: '内因',
    officialSmall: '七情の概念と五臓への影響',
    normalizedTheme: '病因論',
    aliases: [],
    relatedThemes: ['roku-in', 'zo-sho'],
    studyPoint: '喜（心）・怒（肝）・憂（肺）・思（脾）・悲（肺）・恐（腎）・驚（腎）と五臓の対応を暗記。七情が過度になると各臓の気機を乱すことを理解。病因論の内因として整理。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'toyo-rekishi',
    name: '東洋医学の歴史',
    subject: 'oriental-overview',
    examRounds: [29, 31, 33],
    importance: 'C',
    officialLarge: '東洋医学の基礎理論',
    officialMedium: '東洋医学の歴史',
    officialSmall: '主要な医学書と医家',
    normalizedTheme: '東洋医学の歴史',
    aliases: [],
    relatedThemes: ['in-yo-ron', 'go-gyo-ron'],
    studyPoint: '黄帝内経・難経・傷寒論・神農本草経などの成立年代と内容概要を把握。張仲景（傷寒論）・李時珍（本草綱目）など重要医家と著作の対応を整理。日本への伝来も確認。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 衛生学・公衆衛生学 ──────────────────────────
  t({
    id: 'kenko-nihon-21',
    name: '健康日本21',
    subject: 'hygiene',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'A',
    officialLarge: '健康増進',
    officialMedium: '健康づくり対策',
    officialSmall: '健康日本21（各次）の目標と評価',
    normalizedTheme: '健康増進政策',
    aliases: ['健康日本21（第三次）', '健康増進計画'],
    relatedThemes: ['seikatsu-shukan-byo'],
    studyPoint: '健康日本21の各次（第一次〜第三次）の期間・目標を整理。第三次（2024〜2035年）の基本方針を把握。BMI・歩数・飲酒量などの数値目標が出題される。6年連続出題。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'kansen-sho',
    name: '感染症',
    subject: 'hygiene',
    examRounds: [29, 30, 31, 32, 33],
    importance: 'A',
    officialLarge: '感染症',
    officialMedium: '感染症の予防と対策',
    officialSmall: '感染症法による分類・届出・対応',
    normalizedTheme: '感染症対策',
    aliases: ['感染症法', '新興感染症', '再興感染症'],
    relatedThemes: ['seikatsu-shukan-byo', 'menekigaku'],
    studyPoint: '感染症法の1〜5類分類と届出期限を表で整理。主要感染症（結核・コレラ・ペスト等）の病原体・感染経路・潜伏期間を把握。院内感染防止対策・標準予防策も出題。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'seikatsu-shukan-byo',
    name: '生活習慣病',
    subject: 'hygiene',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'A',
    officialLarge: '疾病の予防',
    officialMedium: '生活習慣病',
    officialSmall: 'メタボリックシンドロームと特定健診・特定保健指導',
    normalizedTheme: '生活習慣病対策',
    aliases: ['メタボリックシンドローム', '特定健診'],
    relatedThemes: ['kenko-nihon-21'],
    studyPoint: 'メタボリックシンドロームの診断基準（腹囲・血圧・血糖・脂質の数値）を暗記。特定健診・特定保健指導の対象者・内容・目的を理解。一次・二次・三次予防の概念も整理。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 解剖学 ────────────────────────────────────
  t({
    id: 'kin-kishi-teishi',
    name: '筋の起始停止',
    subject: 'anatomy',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '筋系',
    officialMedium: '全身の骨格筋',
    officialSmall: '各筋の起始・停止・作用・支配神経',
    normalizedTheme: '筋系',
    aliases: [],
    relatedThemes: ['kansetsu-kozo', 'no-shinkei'],
    studyPoint: '上肢（三角筋・上腕二頭筋・大胸筋等）・下肢（大腿四頭筋・腓腹筋・中殿筋等）・体幹（脊柱起立筋等）の起始・停止・作用を解剖図と照合しながら暗記。6年連続出題。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'no-shinkei',
    name: '脳神経',
    subject: 'anatomy',
    examRounds: [29, 30, 31, 32, 34],
    importance: 'A',
    officialLarge: '神経系',
    officialMedium: '末梢神経系',
    officialSmall: '脳神経（12対）の名称・番号・機能分類',
    normalizedTheme: '神経系',
    aliases: ['12脳神経', '脳神経12対'],
    relatedThemes: ['jiritsu-shinkei', 'kin-kishi-teishi'],
    studyPoint: 'Ⅰ嗅〜Ⅻ舌下神経の名称・番号・機能種別（感覚/運動/混合/副交感）を表で暗記。顔面神経（Ⅶ）・迷走神経（Ⅹ）の詳細が特に頻出。出走部位も整理。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'kansetsu-kozo',
    name: '関節の構造',
    subject: 'anatomy',
    examRounds: [29, 30, 31, 33],
    importance: 'B',
    officialLarge: '骨格系',
    officialMedium: '関節',
    officialSmall: '関節の種類・構造・可動性',
    normalizedTheme: '骨格系',
    aliases: [],
    relatedThemes: ['kin-kishi-teishi'],
    studyPoint: '単軸・二軸・多軸関節の種類（蝶番・球・車軸・楕円・鞍・平面関節）と代表的な関節例を整理。靭帯の名称と機能も頻出。肩関節・膝関節の詳細を優先学習。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 生理学 ────────────────────────────────────
  t({
    id: 'jiritsu-shinkei',
    name: '自律神経',
    subject: 'physiology',
    examRounds: [29, 30, 31, 32, 33],
    importance: 'A',
    officialLarge: '神経系の機能',
    officialMedium: '自律神経系',
    officialSmall: '交感神経・副交感神経の作用比較',
    normalizedTheme: '自律神経系',
    aliases: [],
    relatedThemes: ['no-shinkei', 'junkan-kino'],
    studyPoint: '交感神経と副交感神経の各臓器への作用を比較表で整理（瞳孔・心拍・血管・消化・膀胱等）。アドレナリン受容体（α1・α2・β1・β2）の基本も押さえる。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'junkan-kino',
    name: '循環機能',
    subject: 'physiology',
    examRounds: [29, 30, 32, 34],
    importance: 'B',
    officialLarge: '循環機能',
    officialMedium: '心臓の機能と血液循環',
    officialSmall: '心臓の構造・刺激伝導系・体循環と肺循環',
    normalizedTheme: '循環器系',
    aliases: [],
    relatedThemes: ['jiritsu-shinkei'],
    studyPoint: '刺激伝導系（洞房結節→房室結節→ヒス束→左右脚→プルキンエ線維）と体循環・肺循環の流れを暗記。心拍出量・血圧調節（レニン・アンジオテンシン系等）も整理。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 関係法規 ────────────────────────────────────
  t({
    id: 'kanke-hokki',
    name: '関係法規',
    subject: 'regulations',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'A',
    officialLarge: '関係法規',
    officialMedium: 'あん摩マッサージ指圧師、はり師、きゅう師等に関する法律',
    officialSmall: '業務範囲・免許・施術所の管理・広告規制・罰則',
    normalizedTheme: 'あはき法',
    aliases: ['あはき法', 'あん摩法'],
    relatedThemes: [],
    studyPoint: '業務独占と名称独占の区別、免許の要件・欠格事由、業務停止・免許取消の規定を整理。施術所の届出要件と衛生管理基準・広告規制の内容が頻出。6年連続出題。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── はり理論 ────────────────────────────────────
  t({
    id: 'hari-risk-kanri',
    name: '鍼のリスク管理',
    subject: 'acupuncture-theory',
    examRounds: [29, 30, 31, 32, 33],
    importance: 'A',
    officialLarge: 'リスク管理',
    officialMedium: '鍼療法の医療過誤と副作用',
    officialSmall: '折鍼・内出血・神経損傷・気胸・感染の原因と対応',
    normalizedTheme: 'リスク管理',
    aliases: [],
    relatedThemes: ['hari-shigeki-ryo', 'kyu-fukusayo'],
    studyPoint: '折鍼・内出血・神経損傷・気胸・感染それぞれの原因・予防・対応を整理。消毒法（アルコール・オートクレーブ等）の適用場面も出題。禁鍼部位と施術前確認事項も確認。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'hari-shigeki-ryo',
    name: '鍼の刺激量',
    subject: 'acupuncture-theory',
    examRounds: [29, 31, 32, 33],
    importance: 'B',
    officialLarge: '鍼の操作',
    officialMedium: '刺激の調節',
    officialSmall: '刺激量を構成する要素と補瀉法',
    normalizedTheme: '鍼操作',
    aliases: [],
    relatedThemes: ['hari-risk-kanri'],
    studyPoint: '鍼の太さ・長さ・刺入深度・角度・手技（雀啄・旋捻・置鍼等）・留針時間の組み合わせによる刺激量の調節を理解。補瀉の原則（迎随・呼吸・開闔・陰陽補瀉）も整理。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── きゅう理論 ────────────────────────────────────
  t({
    id: 'kyu-fukusayo',
    name: '灸の副作用',
    subject: 'moxibustion-theory',
    examRounds: [29, 31, 32, 33],
    importance: 'B',
    officialLarge: 'リスク管理',
    officialMedium: '灸療法の医療過誤と副作用',
    officialSmall: '施灸による熱傷と禁灸部位',
    normalizedTheme: 'リスク管理',
    aliases: [],
    relatedThemes: ['hari-risk-kanri'],
    studyPoint: '熱傷の深度（Ⅰ度・Ⅱ度・Ⅲ度）の判別と処置を整理。禁灸部位（大血管・目・顔面等）を暗記。無瘢痕灸と有瘢痕灸の特徴と適応。施灸量の調節法も出題。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 東洋医学臨床論 ────────────────────────────────
  t({
    id: 'ben-sho-ron-chi',
    name: '弁証論治',
    subject: 'oriental-clinical',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'A',
    officialLarge: '弁証論治',
    officialMedium: '八綱弁証',
    officialSmall: '陰陽・表裏・寒熱・虚実の弁別と治則',
    normalizedTheme: '弁証論治',
    aliases: ['八綱弁証', '証'],
    relatedThemes: ['kei-myaku-byo-sho', 'in-yo-ron', 'zo-sho'],
    studyPoint: '八綱弁証（陰陽・表裏・寒熱・虚実）が最頻出。各弁証の症候を対比表で整理。臓腑弁証・気血津液弁証・経絡弁証の概要も把握。「証」概念の理解が前提。6年連続出題。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'kei-myaku-byo-sho',
    name: '経絡病証',
    subject: 'oriental-clinical',
    examRounds: [29, 30, 32, 33],
    importance: 'B',
    officialLarge: '弁証論治',
    officialMedium: '経絡弁証',
    officialSmall: '十二経脈の病証（是動病・所生病）',
    normalizedTheme: '弁証論治',
    aliases: ['是動病', '所生病'],
    relatedThemes: ['ben-sho-ron-chi', 'juni-kei-myaku'],
    studyPoint: '霊枢「経脈篇」の是動病・所生病の概念を理解。各経脈の病証の特徴（症状パターン）を経脈ごとに整理。経絡弁証と臓腑弁証の相互関係も押さえる。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 臨床医学総論 ────────────────────────────────
  t({
    id: 'menekigaku',
    name: '免疫学',
    subject: 'clinical-general',
    examRounds: [29, 30, 32, 33],
    importance: 'B',
    officialLarge: '疾患の成立と生体反応',
    officialMedium: '免疫機構',
    officialSmall: '自然免疫・獲得免疫・アレルギー・自己免疫疾患',
    normalizedTheme: '免疫学',
    aliases: [],
    relatedThemes: ['kansen-sho'],
    studyPoint: '自然免疫（NK細胞・マクロファージ等）と獲得免疫（T細胞・B細胞）の役割を整理。アレルギーの分類（Ⅰ〜Ⅳ型）と代表疾患を対応付けて暗記。補体・MHCの概念も確認。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cg-vital-physical',
    name: 'バイタルサインとフィジカルアセスメント',
    subject: 'clinical-general',
    examRounds: [29, 31, 32, 33],
    importance: 'A',
    officialLarge: '診察法',
    officialMedium: '診察の基本',
    officialSmall: 'バイタルサイン・視診・触診・打診・聴診・計測',
    normalizedTheme: '診察法',
    aliases: ['視触打聴診', '心音聴診'],
    relatedThemes: ['cg-kensa-shindan', 'menekigaku'],
    studyPoint: '成人バイタルの正常値（体温・脈拍60〜100・呼吸12〜20・血圧・SpO2）と頻脈/徐脈の原因を整理。心臓弁の聴診部位（大動脈弁：第2肋間胸骨右縁、僧帽弁：心尖部）、声音振盪の増強・減弱、四肢周径の計測点も頻出。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cg-kensa-shindan',
    name: '臨床検査・画像診断・腫瘍マーカー',
    subject: 'clinical-general',
    examRounds: [29, 31, 32, 33],
    importance: 'A',
    officialLarge: '臨床検査',
    officialMedium: '検査法の種類と意義',
    officialSmall: '生化学検査・心電図・画像診断・腫瘍マーカー',
    normalizedTheme: '臨床検査',
    aliases: ['CEA', 'AFP', 'PSA', 'CA19-9'],
    relatedThemes: ['cg-vital-physical'],
    studyPoint: '臓器別の腫瘍マーカー（PSA＝前立腺、AFP＝肝細胞がん、CA19-9＝膵・胆道、CA125＝卵巣、CEA＝大腸）を対応で暗記。被曝の有無（MRI・超音波はなし、X線・CT・PET・シンチはあり）、心電図のST低下＝心筋虚血も整理。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cg-kyukyu-bls',
    name: '救急医療・一次救命処置・ショック',
    subject: 'clinical-general',
    examRounds: [30, 32],
    importance: 'B',
    officialLarge: '治療法',
    officialMedium: '救急処置',
    officialSmall: '一次救命処置（BLS）・AED・ショックの分類',
    normalizedTheme: '救急医療',
    aliases: ['BLS', 'AED', 'ショック'],
    relatedThemes: ['cg-vital-physical'],
    studyPoint: '胸骨圧迫は100〜120回/分・深さ約5cm（6cmを超えない）・圧迫30：換気2。AEDは一般市民・施術者も使用可。ショックの分類（循環血液量減少性・心原性・血液分布異常性・閉塞性）とショックの5徴を整理。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cg-chiryo-gaku',
    name: '治療学の基礎',
    subject: 'clinical-general',
    examRounds: [33, 34],
    importance: 'C',
    officialLarge: '治療法',
    officialMedium: '治療学総論',
    officialSmall: '原因療法・対症療法・根治療法・緩和ケア',
    normalizedTheme: '治療学',
    aliases: ['緩和ケア', 'ターミナルケア'],
    relatedThemes: ['cg-kyukyu-bls'],
    studyPoint: '原因療法・対症療法・根治療法・補充療法の区別を具体例で整理。緩和ケア／ターミナルケアの目標は苦痛緩和とQOL維持であり、根治・延命が目標ではない点を押さえる。意思決定は医師と患者本人が中心。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cg-innai-kansen',
    name: '院内感染対策・標準予防策',
    subject: 'clinical-general',
    examRounds: [29],
    importance: 'C',
    officialLarge: '疾患の成立と生体反応',
    officialMedium: '感染と生体防御',
    officialSmall: '医療関連感染・標準予防策・手指衛生',
    normalizedTheme: '感染対策',
    aliases: ['スタンダードプリコーション', '医療関連感染'],
    relatedThemes: ['menekigaku', 'kansen-sho'],
    studyPoint: '院内感染は入院後おおむね48時間以降の感染。標準予防策はすべての患者の血液・体液・排泄物・粘膜・損傷皮膚を感染源とみなす。手指衛生が最も基本的かつ重要な対策。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 医療概論 ────────────────────────────────────
  t({
    id: 'mo-iryo-hoken-seido',
    name: '医療保険制度と国民医療費',
    subject: 'medical-overview',
    examRounds: [29, 30, 31, 33],
    importance: 'A',
    officialLarge: '医療の提供体制',
    officialMedium: '医療保障制度',
    officialSmall: '医療保険の種類・国民医療費の範囲',
    normalizedTheme: '医療保障制度',
    aliases: ['国民医療費', '被用者保険', '国民健康保険'],
    relatedThemes: ['mo-kaigo-hoken', 'mo-iryo-teikyo'],
    studyPoint: '被用者保険（協会けんぽ・組合健保・共済・船員）と国民健康保険（自営業者等）の区別、加入者最多は協会けんぽ。国民医療費に含まれないもの（正常分娩・健康診断・予防接種・差額ベッド代）を暗記。6年連続出題。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'mo-iryo-teikyo',
    name: '医療提供体制（医療法・医療計画）',
    subject: 'medical-overview',
    examRounds: [29, 32],
    importance: 'B',
    officialLarge: '医療の提供体制',
    officialMedium: '医療法と医療提供施設',
    officialSmall: '医療計画（5疾病5事業）・病院の機能分化',
    normalizedTheme: '医療提供体制',
    aliases: ['5疾病5事業', '地域医療支援病院', '特定機能病院'],
    relatedThemes: ['mo-iryo-hoken-seido', 'mo-nanbyo'],
    studyPoint: '医療計画の5疾病（がん・脳卒中・急性心筋梗塞・糖尿病・精神疾患）5事業（救急・災害・へき地・周産期・小児）は2次医療圏ごとに策定。地域医療支援病院・特定機能病院の要件と、医療安全支援センターの根拠法（医療法）を整理。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'mo-nanbyo',
    name: '難病対策',
    subject: 'medical-overview',
    examRounds: [32, 34],
    importance: 'B',
    officialLarge: '医療の提供体制',
    officialMedium: '公費負担医療',
    officialSmall: '指定難病と難病医療費助成制度',
    normalizedTheme: '難病対策',
    aliases: ['指定難病', '難病法'],
    relatedThemes: ['mo-iryo-teikyo'],
    studyPoint: '難病の医療費助成の主な役割は研究の推進で、社会福祉・公衆衛生ではない。指定難病は診断基準が確立し患者数が一定以下などの要件を満たすもの。受給者証所持者数の多い疾患の傾向も確認。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'mo-informed-consent',
    name: 'インフォームド・コンセントと患者中心の医療',
    subject: 'medical-overview',
    examRounds: [29, 30, 31, 33],
    importance: 'A',
    officialLarge: '医の倫理',
    officialMedium: '医師患者関係',
    officialSmall: 'インフォームド・コンセント・パターナリズム・患者役割',
    normalizedTheme: '医師患者関係',
    aliases: ['自己決定権', 'パターナリズム', 'セカンドオピニオン'],
    relatedThemes: ['mo-i-no-rinri', 'mo-team-iryo'],
    studyPoint: 'インフォームド・コンセントは患者の自律・自己決定権の尊重に基づく。パターナリズム（父権主義）は医療者が患者に代わって決定する態度で、ICと対立する概念。パーソンズの患者役割・サックマンの病気行動の段階も出題。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'mo-team-iryo',
    name: 'チーム医療',
    subject: 'medical-overview',
    examRounds: [31, 32],
    importance: 'B',
    officialLarge: '医療の提供体制',
    officialMedium: '医療従事者の連携',
    officialSmall: 'チーム医療の意義と多職種連携',
    normalizedTheme: 'チーム医療',
    aliases: ['多職種連携', '職種間連携'],
    relatedThemes: ['mo-informed-consent'],
    studyPoint: 'チーム医療で望ましいのは職種間の目的・情報の共有と対等な連携。職種間の固定した上下関係、リーダーの固定、患者を意思決定から排除することは不適切。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'mo-i-no-rinri',
    name: '医の倫理・生命倫理',
    subject: 'medical-overview',
    examRounds: [31, 33, 34],
    importance: 'B',
    officialLarge: '医の倫理',
    officialMedium: '医療倫理の原則',
    officialSmall: '倫理綱領・国際宣言・ターミナルケア',
    normalizedTheme: '医の倫理',
    aliases: ['ヘルシンキ宣言', 'ジュネーブ宣言', 'リスボン宣言'],
    relatedThemes: ['mo-informed-consent'],
    studyPoint: '主要宣言の対応（ヘルシンキ＝医学研究倫理、ジュネーブ＝医師の誓い、リスボン＝患者の権利、アルマ・アタ＝プライマリヘルスケア）を暗記。ターミナルケアの目標はQOL維持と苦痛緩和。あはき施術者の倫理的姿勢も問われる。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'mo-kaigo-hoken',
    name: '介護保険制度と社会保障',
    subject: 'medical-overview',
    examRounds: [29, 30, 32, 33],
    importance: 'A',
    officialLarge: '医療の提供体制',
    officialMedium: '社会保障制度',
    officialSmall: '介護保険の保険者・被保険者・ケアマネジメント',
    normalizedTheme: '社会保障制度',
    aliases: ['介護支援専門員', 'ケアマネジャー', '公費医療'],
    relatedThemes: ['mo-iryo-hoken-seido'],
    studyPoint: '介護保険の保険者は市町村・特別区（国・都道府県ではない）。第1号被保険者（65歳以上）・第2号被保険者（40〜64歳の医療保険加入者）を区別。ケアプラン作成は介護支援専門員。労働者災害補償保険は公費医療ではなく労働保険。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 病理学概論 ──────────────────────────────────
  t({
    id: 'pa-junkan-shogai',
    name: '循環障害',
    subject: 'pathology',
    examRounds: [29, 30, 31, 33, 34],
    importance: 'A',
    officialLarge: '病理学総論',
    officialMedium: '循環障害',
    officialSmall: '充血・うっ血・虚血・梗塞・血栓・塞栓・浮腫・DIC',
    normalizedTheme: '循環障害',
    aliases: ['梗塞', '塞栓症', '血栓症', '浮腫'],
    relatedThemes: ['pa-ensho', 'pa-saibo-shogai'],
    studyPoint: '貧血性梗塞（白色：心・腎・脾）と出血性梗塞（赤色：肺・腸）を区別。塞栓の種類（血栓性＝深部静脈血栓→肺塞栓、脂肪＝骨折後、空気、羊水）。浮腫の4機序（毛細血管内圧上昇・膠質浸透圧低下・血管透過性亢進・リンパ還流障害）とDICを整理。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'pa-ensho',
    name: '炎症',
    subject: 'pathology',
    examRounds: [30, 31, 32, 34],
    importance: 'A',
    officialLarge: '病理学総論',
    officialMedium: '炎症',
    officialSmall: '急性炎症・慢性炎症・炎症の組織学的分類',
    normalizedTheme: '炎症',
    aliases: ['肉芽腫性炎', '線維素性炎', '化膿性炎'],
    relatedThemes: ['pa-junkan-shogai', 'pa-kansen-meneki'],
    studyPoint: '炎症の5徴（発赤・腫脹・発熱・疼痛・機能障害）。急性炎症は好中球、慢性炎症はリンパ球・形質細胞・マクロファージが主体。肉芽腫性炎（類上皮細胞・ラングハンス巨細胞）の代表は結核・サルコイドーシス・ハンセン病。線維素性炎はフィブリン滲出が特徴。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'pa-shuyo',
    name: '腫瘍',
    subject: 'pathology',
    examRounds: [30, 31, 32, 34],
    importance: 'A',
    officialLarge: '病理学総論',
    officialMedium: '腫瘍',
    officialSmall: '良性・悪性の区別・前癌病変・TNM分類・発癌',
    normalizedTheme: '腫瘍',
    aliases: ['前癌病変', 'TNM分類', 'がんとウイルス'],
    relatedThemes: ['pa-kansen-meneki'],
    studyPoint: '前癌病変と対応するがん（子宮頸部異形成→子宮頸がん、大腸腺腫→大腸がん、バレット食道→食道腺がん、肝硬変→肝細胞がん）。TNM分類（T＝原発腫瘍、N＝所属リンパ節、M＝遠隔転移）。がんとウイルス（HBV/HCV→肝細胞がん、HPV→子宮頸がん、EBV→バーキットリンパ腫）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'pa-kansen-meneki',
    name: '感染症・免疫・アレルギー',
    subject: 'pathology',
    examRounds: [29, 30, 31, 32],
    importance: 'A',
    officialLarge: '病理学総論',
    officialMedium: '感染と免疫',
    officialSmall: '感染症法の分類・易感染性・アレルギーの分類',
    normalizedTheme: '感染と免疫',
    aliases: ['日和見感染', 'Ⅳ型アレルギー', '一次免疫応答'],
    relatedThemes: ['pa-ensho', 'menekigaku'],
    studyPoint: '感染症法の1〜5類分類、易感染性の原因（糖尿病・ステロイド・抗がん剤・HIV）。初感染で最初に上昇するのはIgM（一次応答）、再感染ではIgG。Th1→細胞性免疫→Ⅳ型（遅延型：ツベルクリン反応・接触性皮膚炎）。DNAウイルスとRNAウイルスの区別。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'pa-saibo-shogai',
    name: '細胞傷害・変性・壊死',
    subject: 'pathology',
    examRounds: [32, 34],
    importance: 'B',
    officialLarge: '病理学総論',
    officialMedium: '細胞・組織の障害',
    officialSmall: '変性・壊死（凝固・融解・乾酪）・アポトーシス・細胞老化',
    normalizedTheme: '細胞傷害',
    aliases: ['凝固壊死', '融解壊死', '乾酪壊死', 'ヘイフリック限界'],
    relatedThemes: ['pa-junkan-shogai', 'pa-taisha-ijo'],
    studyPoint: '壊死の型と好発臓器（凝固壊死＝心筋梗塞、融解壊死＝脳、乾酪壊死＝結核、脂肪壊死＝膵炎）。アポトーシス（プログラム細胞死・炎症を伴わない）と壊死の違い。細胞老化ではヘイフリック限界により分裂能が低下する。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'pa-iden',
    name: '遺伝性疾患と遺伝の基礎',
    subject: 'pathology',
    examRounds: [29, 30],
    importance: 'B',
    officialLarge: '病理学総論',
    officialMedium: '先天異常',
    officialSmall: '遺伝形式・染色体異常・DNAと蛋白合成',
    normalizedTheme: '先天異常',
    aliases: ['常染色体優性', 'X連鎖劣性'],
    relatedThemes: ['pa-saibo-shogai'],
    studyPoint: '常染色体優性（顕性）：ハンチントン病・家族性大腸腺腫症・マルファン症候群。常染色体劣性（潜性）：フェニルケトン尿症・嚢胞性線維症。X連鎖劣性：血友病A・デュシェンヌ型筋ジストロフィー。DNAの二重らせん・塩基対（A-T、G-C）とS期の複製も確認。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'pa-taisha-ijo',
    name: '代謝異常・物質沈着',
    subject: 'pathology',
    examRounds: [32, 33],
    importance: 'B',
    officialLarge: '病理学総論',
    officialMedium: '代謝障害',
    officialSmall: '糖・脂質・色素・尿酸などの代謝異常と沈着',
    normalizedTheme: '代謝障害',
    aliases: ['粥状動脈硬化', '痛風', 'ヘモジデローシス'],
    relatedThemes: ['pa-saibo-shogai'],
    studyPoint: '沈着物と病態の対応（粥状動脈硬化→コレステロール、痛風→尿酸〈プリン代謝異常〉、黄疸→ビリルビン〈色素代謝異常〉、ヘモジデローシス→鉄）。黄色腫は脂質代謝異常。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'pa-shippei-keika',
    name: '疾病の経過・転帰と疾患の性差',
    subject: 'pathology',
    examRounds: [29, 32, 33],
    importance: 'B',
    officialLarge: '病理学総論',
    officialMedium: '疾病の概念',
    officialSmall: '疾病の経過（前駆期・極期・回復期）・転帰・性差',
    normalizedTheme: '疾病の概念',
    aliases: ['寛解', '瘢痕治癒', '4F'],
    relatedThemes: ['pa-saibo-shogai'],
    studyPoint: '疾病の経過（潜伏期→前駆期〈不定愁訴〉→極期→回復期）と転帰（完全治癒・不完全治癒〈瘢痕・機能障害〉・慢性化・死亡）。女性に多い疾患（SLE・橋本病・関節リウマチ・骨粗鬆症・胆石〈4F〉）、男性に多い疾患（痛風・COPD・十二指腸潰瘍）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 臨床医学各論 ────────────────────────────────
  t({
    id: 'cs-nokekkan',
    name: '脳血管疾患・高次脳機能障害・めまい',
    subject: 'clinical-specific',
    examRounds: [29, 30, 31, 33, 34],
    importance: 'A',
    officialLarge: '神経系疾患',
    officialMedium: '脳血管障害',
    officialSmall: '脳梗塞・脳出血・TIA・失語・半側空間無視・めまい',
    normalizedTheme: '脳血管障害',
    aliases: ['被殻出血', 'ブローカ失語', '半側空間無視', 'BPPV'],
    relatedThemes: ['cs-ninchisho', 'cs-parkinson'],
    studyPoint: '高血圧性脳出血の最好発部位は被殻。左中大脳動脈梗塞（右利き）→失語症、右半球病変→左半側空間無視。TIAは症状が24時間以内に消失しMRIで梗塞巣を認めない。末梢性めまい（回転性・耳症状あり）と中枢性めまい（持続性・平衡障害強い）の鑑別。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cs-ninchisho',
    name: '認知症',
    subject: 'clinical-specific',
    examRounds: [29, 31, 32, 33, 34],
    importance: 'A',
    officialLarge: '神経系疾患',
    officialMedium: '認知症性疾患',
    officialSmall: 'アルツハイマー型・レビー小体型・血管性・前頭側頭型の鑑別',
    normalizedTheme: '認知症',
    aliases: ['アルツハイマー病', 'レビー小体型認知症', 'ピック病'],
    relatedThemes: ['cs-nokekkan', 'cs-parkinson'],
    studyPoint: '初発症状で鑑別：近時記憶障害→アルツハイマー型（海馬・側頭葉萎縮、アミロイドβ・タウ蓄積）、幻視・認知の変動・パーキンソン症状→レビー小体型、人格変化・脱抑制→前頭側頭型、段階的悪化・まだら認知症→血管性。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cs-parkinson',
    name: 'パーキンソン病・不随意運動',
    subject: 'clinical-specific',
    examRounds: [30, 32, 33, 34],
    importance: 'A',
    officialLarge: '神経系疾患',
    officialMedium: '神経変性疾患',
    officialSmall: 'パーキンソン病の4大症状・自律神経症状・不随意運動の種類',
    normalizedTheme: 'パーキンソン病',
    aliases: ['安静時振戦', '歯車様固縮', 'すくみ足'],
    relatedThemes: ['cs-ninchisho', 'cs-shinkeikin'],
    studyPoint: '4大症状は安静時振戦（丸薬まるめ様）・筋固縮（歯車様）・無動／寡動・姿勢反射障害。仮面様顔貌・小刻み歩行・すくみ足。非運動症状（便秘・起立性低血圧・嗅覚障害・抑うつ）。本態性振戦は動作時振戦で区別。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cs-shinkeikin',
    name: '神経筋疾患・末梢神経障害',
    subject: 'clinical-specific',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '神経系疾患',
    officialMedium: '運動ニューロン疾患・末梢神経障害・筋疾患',
    officialSmall: 'ALS・ギラン・バレー症候群・筋ジストロフィー・絞扼性神経障害',
    normalizedTheme: '神経筋疾患',
    aliases: ['筋萎縮性側索硬化症', 'デュシェンヌ型', '手根管症候群'],
    relatedThemes: ['cs-parkinson', 'cs-sekitsui'],
    studyPoint: 'ALSは上位・下位運動ニューロンの障害（筋萎縮＋腱反射亢進が共存、感覚・眼球運動・膀胱直腸は保たれる）。ギラン・バレー症候群は先行感染後の急性脱髄。デュシェンヌ型はX連鎖劣性・ガワーズ徴候・腓腹筋仮性肥大。末梢神経麻痺（下垂手＝橈骨、猿手＝正中、鷲手＝尺骨）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cs-seishin',
    name: '精神疾患',
    subject: 'clinical-specific',
    examRounds: [30, 31, 32, 33, 34],
    importance: 'A',
    officialLarge: '精神疾患',
    officialMedium: '主要な精神障害',
    officialSmall: '統合失調症・気分障害・不安障害・発達障害・認知行動療法',
    normalizedTheme: '精神疾患',
    aliases: ['パニック障害', '自閉スペクトラム症', 'うつ病'],
    relatedThemes: ['cs-ninchisho'],
    studyPoint: 'パニック障害は突然のパニック発作（数分〜30分で消退）＋予期不安＋広場恐怖で、SSRIと認知行動療法が有効。統合失調症の症状（妄想・幻聴・させられ体験）と区別。うつ病の回復初期は意欲回復に伴い自殺企図リスクが高まる。ASDとADHDの主徴の違い。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cs-hentai-kansetsu',
    name: '変形性関節症・関節リウマチ・骨代謝疾患',
    subject: 'clinical-specific',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '運動器系疾患',
    officialMedium: '関節・骨の疾患',
    officialSmall: '変形性関節症・関節リウマチ・骨粗鬆症・くる病',
    normalizedTheme: '運動器疾患',
    aliases: ['変形性膝関節症', 'RA', '骨粗鬆症'],
    relatedThemes: ['cs-sekitsui', 'cs-gaisho'],
    studyPoint: '変形性関節症のX線4徴（関節裂隙狭小化・骨棘形成・軟骨下骨硬化・骨嚢胞）。関節リウマチの特徴（早朝こわばり・対称性小関節炎・MP関節尺側偏位・スワンネック・ボタン穴変形・環軸椎亜脱臼）。骨粗鬆症の三大骨折部位（椎体・橈骨遠位端・大腿骨近位部）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cs-sekitsui',
    name: '脊椎疾患・神経根障害と整形外科的徒手検査',
    subject: 'clinical-specific',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '運動器系疾患',
    officialMedium: '脊椎・末梢神経の障害',
    officialSmall: '椎間板ヘルニア・脊柱管狭窄症・頸椎症・徒手検査法',
    normalizedTheme: '脊椎疾患',
    aliases: ['腰椎椎間板ヘルニア', '脊柱管狭窄症', 'デルマトーム'],
    relatedThemes: ['cs-hentai-kansetsu', 'cs-shinkeikin'],
    studyPoint: '椎間板ヘルニア（若年・前屈で増悪・SLR陽性）と脊柱管狭窄症（高齢・間欠性跛行・前屈で軽快）の鑑別。神経根障害：L5＝足背・足関節背屈、S1＝足底・アキレス腱反射消失、C6＝母指〜前腕橈側・腕橈骨筋反射低下。徒手検査（ラックマン＝前十字靱帯、マクマレー＝半月板、スパーリング＝頸椎神経根）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cs-gaisho',
    name: '外傷・脱臼・スポーツ障害',
    subject: 'clinical-specific',
    examRounds: [29, 30, 31, 32, 34],
    importance: 'A',
    officialLarge: '運動器系疾患',
    officialMedium: '外傷と障害',
    officialSmall: '骨折・脱臼・応急処置（RICE）・スポーツ外傷とスポーツ障害',
    normalizedTheme: '外傷・スポーツ障害',
    aliases: ['コーレス骨折', '上腕骨顆上骨折', 'オスグッド病'],
    relatedThemes: ['cs-sekitsui', 'cs-hentai-kansetsu'],
    studyPoint: 'RICE処置（Rest・Ice・Compression・Elevation）は軟部組織損傷の急性期。コーレス骨折（橈骨遠位端・手掌をついて転倒）、上腕骨顆上骨折（小児・正中神経障害を合併）、肩関節前方脱臼（腋窩神経障害・方形肩）。スポーツ外傷（急性）とスポーツ障害（使い過ぎ）の区別。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cs-ketsueki',
    name: '血液疾患',
    subject: 'clinical-specific',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '血液・造血器系疾患',
    officialMedium: '貧血・白血病・出血性疾患',
    officialSmall: '鉄欠乏性貧血・巨赤芽球性貧血・白血病・ITP・血友病',
    normalizedTheme: '血液疾患',
    aliases: ['鉄欠乏性貧血', '急性骨髄性白血病', 'ITP'],
    relatedThemes: ['cs-kansen'],
    studyPoint: '貧血の分類：小球性低色素性（鉄欠乏性：血清フェリチン低下・TIBC上昇・匙状爪）、大球性（巨赤芽球性：ビタミンB12・葉酸欠乏）、正球性（溶血性・再生不良性）。急性骨髄性白血病はAuer小体・汎血球減少→易感染性。ITPは血小板に対するIgG自己抗体。血友病はX連鎖劣性。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cs-kansen',
    name: '感染症',
    subject: 'clinical-specific',
    examRounds: [29, 31, 32, 33, 34],
    importance: 'A',
    officialLarge: '感染症',
    officialMedium: '主要な感染症',
    officialSmall: 'ウイルス性肝炎・結核・HIV・食中毒・上気道感染症',
    normalizedTheme: '感染症',
    aliases: ['B型肝炎', '肺結核', 'HIV感染症'],
    relatedThemes: ['cs-shokaki', 'cs-ketsueki'],
    studyPoint: 'ウイルス性肝炎の感染経路（A・E型＝経口、B・C型＝血液・体液）。肺結核（空気感染・N95マスク・陰圧個室）。HIV／AIDSの日和見感染。食中毒の原因別特徴（カンピロバクター・ノロウイルス・腸管出血性大腸菌O157・アニサキス）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cs-shokaki',
    name: '消化器疾患（肝・胆・膵・消化管）',
    subject: 'clinical-specific',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '消化器系疾患',
    officialMedium: '肝胆膵・消化管の疾患',
    officialSmall: '肝硬変・肝炎・膵炎・消化性潰瘍・消化器腫瘍・黄疸',
    normalizedTheme: '消化器疾患',
    aliases: ['肝硬変', '急性膵炎', '黄疸の分類'],
    relatedThemes: ['cs-kansen'],
    studyPoint: '黄疸の分類：溶血性（間接ビリルビン上昇）、肝細胞性、閉塞性（直接ビリルビン上昇＝胆石・膵頭部癌・胆管癌）。肝硬変の合併症（食道静脈瘤・肝性脳症・腹水）。急性膵炎（上腹部痛・血中アミラーゼ／リパーゼ上昇）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cs-junkanki',
    name: '循環器疾患',
    subject: 'clinical-specific',
    examRounds: [30, 31, 32, 34],
    importance: 'A',
    officialLarge: '循環器系疾患',
    officialMedium: '心・血管の疾患',
    officialSmall: '虚血性心疾患・不整脈・心不全・脂質異常症',
    normalizedTheme: '循環器疾患',
    aliases: ['心筋梗塞', '心房細動', '心不全'],
    relatedThemes: ['cs-kokyuki'],
    studyPoint: '虚血性心疾患：狭心症（労作時・ニトログリセリン有効・ST低下）と心筋梗塞（安静時・30分以上・CK-MB・トロポニン上昇・ST上昇）。左心不全→肺うっ血・起座呼吸、右心不全→下肢浮腫・頸静脈怒張・肝腫大。心房細動はP波消失・RR不整。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cs-kokyuki',
    name: '呼吸器疾患',
    subject: 'clinical-specific',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '呼吸器系疾患',
    officialMedium: '気道・肺の疾患',
    officialSmall: 'COPD・気管支喘息・肺炎・気胸・肺結核・肺癌',
    normalizedTheme: '呼吸器疾患',
    aliases: ['COPD', '気管支喘息', '自然気胸'],
    relatedThemes: ['cs-junkanki', 'cs-kansen'],
    studyPoint: 'COPDは閉塞性換気障害（1秒率低下）・喫煙が主因・樽状胸郭。気管支喘息は可逆性気道狭窄・発作性呼気性呼吸困難。自然気胸は若い痩せ型男性に多く突然の胸痛・呼吸困難・患側呼吸音減弱。拘束性換気障害（肺線維症・胸郭運動制限）との区別。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cs-jin-hinyoki',
    name: '腎・泌尿器疾患',
    subject: 'clinical-specific',
    examRounds: [29, 30, 31, 32, 34],
    importance: 'A',
    officialLarge: '腎・泌尿器系疾患',
    officialMedium: '腎・尿路の疾患',
    officialSmall: '腎不全・ネフローゼ症候群・尿路感染症・尿量異常・前立腺肥大',
    normalizedTheme: '腎・泌尿器疾患',
    aliases: ['ネフローゼ症候群', '尿路感染症', '前立腺肥大症'],
    relatedThemes: ['cs-junkanki'],
    studyPoint: 'ネフローゼ症候群の4徴（高度蛋白尿・低アルブミン血症・浮腫・脂質異常症）。乏尿は400mL/日以下、無尿は100mL/日以下、多尿は3L/日以上。前立腺肥大は排出障害（尿勢低下・残尿）、過活動膀胱は蓄尿障害（尿意切迫・頻尿）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cs-naibunpi',
    name: '内分泌・代謝疾患',
    subject: 'clinical-specific',
    examRounds: [29, 31, 32, 33, 34],
    importance: 'A',
    officialLarge: '内分泌・代謝疾患',
    officialMedium: '内分泌腺・代謝の疾患',
    officialSmall: '糖尿病・甲状腺疾患・副腎疾患・脂質異常症・痛風',
    normalizedTheme: '内分泌・代謝疾患',
    aliases: ['糖尿病', 'バセドウ病', '橋本病', 'クッシング症候群'],
    relatedThemes: ['cs-jin-hinyoki'],
    studyPoint: '糖尿病の三大合併症（網膜症・腎症・神経障害）。糖尿病神経障害は最も早期に出現し遠位優位・対称性（手袋靴下型）・アキレス腱反射消失。甲状腺機能亢進症（バセドウ病：頻脈・体重減少・眼球突出）と低下症（橋本病：徐脈・浮腫・易疲労）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'cs-hifu-shuyo',
    name: '皮膚・アレルギー疾患・悪性腫瘍',
    subject: 'clinical-specific',
    examRounds: [30, 31, 32, 33, 34],
    importance: 'B',
    officialLarge: '皮膚系疾患・腫瘍',
    officialMedium: '皮膚・アレルギー・悪性腫瘍',
    officialSmall: '帯状疱疹・アトピー性皮膚炎・アレルギー疾患・各部位のがん',
    normalizedTheme: '皮膚・腫瘍',
    aliases: ['帯状疱疹', 'アナフィラキシー', 'がん統計'],
    relatedThemes: ['cs-kansen', 'cs-shokaki'],
    studyPoint: '帯状疱疹は水痘・帯状疱疹ウイルスの再活性化で神経支配領域（デルマトーム）に一致した片側性の水疱と神経痛。Ⅰ型アレルギー（IgE・肥満細胞・アナフィラキシー）。がん死亡数（男性は肺・大腸・胃、女性は大腸・肺・膵の傾向）。乳がん・骨腫瘍の特徴も確認。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── リハビリテーション医学 ──────────────────────
  t({
    id: 'rh-soron',
    name: 'リハビリテーション総論（ICF・評価法）',
    subject: 'rehabilitation',
    examRounds: [29, 31, 32, 33, 34],
    importance: 'A',
    officialLarge: 'リハビリテーション医学総論',
    officialMedium: '障害の概念と評価',
    officialSmall: 'ICF・リハの4領域・FIM・MMT・関節可動域',
    normalizedTheme: 'リハビリテーション総論',
    aliases: ['ICF', 'FIM', '徒手筋力検査'],
    relatedThemes: ['rh-nosocchu', 'rh-team'],
    studyPoint: 'ICFの構成（心身機能・身体構造／活動／参加、背景因子＝環境因子・個人因子）。リハの4領域（医学的・職業的・社会的・教育的）。FIMの運動項目・認知項目。MMTの段階（3＝重力に抗して全可動域、2＝重力除去位で全可動域）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'rh-nosocchu',
    name: '脳卒中のリハビリテーション',
    subject: 'rehabilitation',
    examRounds: [30, 31, 32, 34],
    importance: 'A',
    officialLarge: 'リハビリテーション医学各論',
    officialMedium: '脳血管障害のリハビリテーション',
    officialSmall: '片麻痺・ブルンストロームステージ・短下肢装具・利き手交換',
    normalizedTheme: '脳卒中リハビリテーション',
    aliases: ['ブルンストロームステージ', '短下肢装具', 'AFO'],
    relatedThemes: ['rh-soron', 'rh-engo-shogai'],
    studyPoint: 'ブルンストロームステージ（Ⅰ＝弛緩・随意運動なし、Ⅱ＝連合反応・共同運動出現、Ⅲ＝共同運動が随意的に最大、Ⅳ＝共同運動から分離開始）。生活期の片麻痺で最も使われる装具はプラスチック短下肢装具（AFO・尖足予防）。重度片麻痺では利き手交換訓練。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'rh-sekizui',
    name: '脊髄損傷のリハビリテーション',
    subject: 'rehabilitation',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: 'リハビリテーション医学各論',
    officialMedium: '脊髄損傷のリハビリテーション',
    officialSmall: '損傷高位別のADL・自律神経過反射・褥瘡予防',
    normalizedTheme: '脊髄損傷リハビリテーション',
    aliases: ['自律神経過反射', '残存機能', '間欠的自己導尿'],
    relatedThemes: ['rh-soron'],
    studyPoint: '損傷高位と残存機能（C4＝電動車椅子・呼吸補助、C6＝手関節背屈で手動車椅子操作、C7＝肘伸展、C8＝手指屈曲）。自律神経過反射はT6以上で発生し、膀胱充満・便秘・褥瘡が誘因→急激な血圧上昇。対応は座位・誘因除去。中心性頸髄損傷は上肢優位の麻痺。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'rh-noseimahi',
    name: '脳性麻痺のリハビリテーション',
    subject: 'rehabilitation',
    examRounds: [29, 30, 31, 32, 33],
    importance: 'A',
    officialLarge: 'リハビリテーション医学各論',
    officialMedium: '小児のリハビリテーション',
    officialSmall: '脳性麻痺の病型分類・GMFCS・合併症',
    normalizedTheme: '脳性麻痺',
    aliases: ['痙直型', 'アテトーゼ型', 'はさみ脚歩行'],
    relatedThemes: ['rh-soron'],
    studyPoint: '脳性麻痺は出生前〜新生児期の非進行性の脳障害による運動・姿勢の障害。病型は痙直型（最多・約70%）・アテトーゼ型（不随意運動・基底核病変）・失調型（小脳）・混合型。痙直型下肢は尖足・股関節内転内旋（はさみ脚歩行）。知的障害・てんかんを合併しやすい。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'rh-shinkei-undoki',
    name: '神経・運動器疾患のリハビリテーション',
    subject: 'rehabilitation',
    examRounds: [29, 30, 31, 32, 33],
    importance: 'A',
    officialLarge: 'リハビリテーション医学各論',
    officialMedium: '神経変性疾患・運動器疾患のリハビリテーション',
    officialSmall: 'パーキンソン病・変形性膝関節症・関節リウマチのリハ',
    normalizedTheme: '神経・運動器リハビリテーション',
    aliases: ['LSVT', '大腿四頭筋訓練', 'Hoehn-Yahr'],
    relatedThemes: ['rh-soron', 'cs-parkinson'],
    studyPoint: 'パーキンソン病リハ：大股・リズミック歩行訓練、視覚・聴覚キュー、LSVT（発声訓練）。Hoehn-Yahr重症度分類（Ⅲ＝姿勢反射障害あり・日常生活自立、Ⅳ＝介助必要、Ⅴ＝車椅子・臥床）。変形性膝関節症は大腿四頭筋（内側広筋）強化・減量・水中歩行。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'rh-engo-shogai',
    name: '摂食嚥下障害・言語障害・高次脳機能障害',
    subject: 'rehabilitation',
    examRounds: [29, 30, 32, 33, 34],
    importance: 'A',
    officialLarge: 'リハビリテーション医学各論',
    officialMedium: '嚥下・言語・高次脳機能のリハビリテーション',
    officialSmall: '嚥下5期・失語症・構音障害・半側空間無視・遂行機能障害',
    normalizedTheme: '嚥下・言語・高次脳機能リハビリテーション',
    aliases: ['嚥下5期', 'ブローカ失語', '半側空間無視'],
    relatedThemes: ['rh-nosocchu', 'rh-team'],
    studyPoint: '嚥下5期（先行期→準備期→口腔期→咽頭期→食道期）。咽頭期は嚥下反射（軟口蓋挙上・喉頭蓋閉鎖）。失語症（ブローカ＝非流暢・理解良好、ウェルニッケ＝流暢・理解不良）と構音障害（発声器官の運動障害）の区別。左半側空間無視は重要物を右側に配置。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'rh-gishi-sogu',
    name: '義肢・装具・切断のリハビリテーション',
    subject: 'rehabilitation',
    examRounds: [30, 31, 32, 34],
    importance: 'A',
    officialLarge: 'リハビリテーション医学各論',
    officialMedium: '切断と義肢装具',
    officialSmall: '断端管理・PTB義足・上肢装具・幻肢痛',
    normalizedTheme: '義肢・装具',
    aliases: ['PTB義足', '断端包帯', '幻肢痛'],
    relatedThemes: ['rh-soron'],
    studyPoint: '断端包帯（弾性包帯）の目的は浮腫予防と断端成形（義足装着準備）。PTB義足は膝蓋腱・膝蓋骨下縁で体重支持（下腿切断）。上肢装具：コックアップスプリント（橈骨神経麻痺の下垂手）。幻肢痛は治癒後も持続し、鏡療法・神経ブロックが有効。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'rh-haiyo-frailty',
    name: '廃用症候群・フレイル・サルコペニア',
    subject: 'rehabilitation',
    examRounds: [29, 33, 34],
    importance: 'B',
    officialLarge: 'リハビリテーション医学総論',
    officialMedium: '不動と高齢者の機能低下',
    officialSmall: '廃用症候群・フレイル（J-CHS基準）・サルコペニア',
    normalizedTheme: '廃用症候群・フレイル',
    aliases: ['J-CHS基準', 'サルコペニア', '生活不活発病'],
    relatedThemes: ['rh-soron'],
    studyPoint: '廃用症候群は不活動による機能低下（筋萎縮・骨粗鬆症・起立性低血圧・褥瘡・深部静脈血栓・沈下性肺炎）。フレイルのJ-CHS基準5項目（体重減少・筋力〈握力〉低下・疲労感・歩行速度低下・身体活動量低下）。サルコペニアは加齢による骨格筋量・筋力の低下。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'rh-naibu-shogai',
    name: '内部障害のリハビリテーション（心臓・呼吸）',
    subject: 'rehabilitation',
    examRounds: [29, 31, 32, 33],
    importance: 'B',
    officialLarge: 'リハビリテーション医学各論',
    officialMedium: '内部障害のリハビリテーション',
    officialSmall: '心臓リハビリテーション・呼吸リハビリテーション',
    normalizedTheme: '内部障害リハビリテーション',
    aliases: ['口すぼめ呼吸', 'NYHA分類', '心臓リハ禁忌'],
    relatedThemes: ['rh-soron', 'cs-junkanki'],
    studyPoint: '呼吸リハは運動療法＋コンディショニング（口すぼめ呼吸で呼気延長・気道虚脱予防、ハフィングで排痰）＋患者教育。心臓リハの禁忌は不安定狭心症・急性心筋炎・急性大動脈解離など安静を要する病態。安定した心不全・心筋梗塞回復期は適応。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'rh-team',
    name: 'リハビリテーションチームと多職種連携・歩行分析',
    subject: 'rehabilitation',
    examRounds: [29, 30, 31, 32, 34],
    importance: 'A',
    officialLarge: 'リハビリテーション医学総論',
    officialMedium: 'リハビリテーションの体系と専門職',
    officialSmall: 'PT・OT・STの役割・MSW・介護支援専門員・歩行分析',
    normalizedTheme: 'リハビリテーションチーム',
    aliases: ['理学療法士', '作業療法士', '言語聴覚士', '分回し歩行'],
    relatedThemes: ['rh-soron'],
    studyPoint: '職種の役割：PT＝基本動作・歩行、OT＝上肢・ADL・利き手交換・自助具、ST＝言語・嚥下訓練、MSW＝退院支援・社会資源調整、介護支援専門員＝介護保険ケアプラン。歩行周期（立脚相約60%・遊脚相約40%）と異常歩行（分回し＝片麻痺、小刻み＝PD、トレンデレンブルグ＝中殿筋筋力低下、鶏歩＝腓骨神経麻痺）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 衛生学・公衆衛生学（追加） ──────────────────
  t({
    id: 'hy-ekigaku',
    name: '疫学・保健統計',
    subject: 'hygiene',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '保健統計・疫学',
    officialMedium: '疫学の方法と指標',
    officialSmall: '罹患率・有病率・研究デザイン・人口動態統計',
    normalizedTheme: '疫学',
    aliases: ['コホート研究', '症例対照研究', '相対危険', '寄与危険'],
    relatedThemes: ['seikatsu-shukan-byo', 'hy-boshi-hoken'],
    studyPoint: '有病率は横断研究で、罹患率はコホート研究（縦断研究）で測定。相対危険度＝比、寄与危険度＝差、オッズ比＝症例対照研究。人口静態統計（国勢調査・5年ごと）と人口動態統計（出生・死亡・婚姻・離婚・死産・毎年）の区別。6年連続出題。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'hy-kansen-yobo',
    name: '感染予防と消毒・滅菌',
    subject: 'hygiene',
    examRounds: [29, 30, 32, 33, 34],
    importance: 'A',
    officialLarge: '感染症',
    officialMedium: '感染予防対策',
    officialSmall: '感染経路別予防策・滅菌と消毒・手指衛生',
    normalizedTheme: '感染予防',
    aliases: ['空気感染予防策', '飛沫感染予防策', 'オートクレーブ'],
    relatedThemes: ['kansen-sho', 'cg-innai-kansen'],
    studyPoint: '感染経路別予防策：空気感染（N95マスク・陰圧個室＝結核・水痘・麻疹）、飛沫感染（サージカルマスク＝インフルエンザ・百日咳）、接触感染（ノロウイルス）。滅菌（全微生物死滅：高圧蒸気・乾熱・EOG・放射線）と消毒（病原体のみ：70%エタノール等）の区別。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'hy-yobo-danal',
    name: '疾病予防の段階と健康指標',
    subject: 'hygiene',
    examRounds: [30, 31, 32, 33, 34],
    importance: 'A',
    officialLarge: '健康増進',
    officialMedium: '予防医学の概念',
    officialSmall: '一次〜三次予防・ハイリスク／ポピュレーションアプローチ',
    normalizedTheme: '予防医学',
    aliases: ['一次予防', '二次予防', 'ハイリスクアプローチ'],
    relatedThemes: ['kenko-nihon-21', 'seikatsu-shukan-byo'],
    studyPoint: '一次予防（発症前：健康増進・特異的予防〈予防接種〉）、二次予防（早期発見・早期治療＝スクリーニング検査）、三次予防（リハビリ・再発防止・機能回復）。ハイリスクアプローチ（高リスク者への個別介入）とポピュレーションアプローチ（集団全体への働きかけ）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'hy-sangyo-hoken',
    name: '産業保健（労働衛生の3管理）',
    subject: 'hygiene',
    examRounds: [30, 33],
    importance: 'B',
    officialLarge: '環境保健・産業保健',
    officialMedium: '労働衛生',
    officialSmall: '作業環境管理・作業管理・健康管理・職業性疾病',
    normalizedTheme: '産業保健',
    aliases: ['3管理', 'じん肺', '特殊健康診断'],
    relatedThemes: ['hy-yobo-danal'],
    studyPoint: '労働衛生の3管理：作業環境管理（換気・測定など環境改善）、作業管理（作業姿勢・方法・保護具の管理で曝露低減）、健康管理（一般・特殊健康診断）。中心となるのは産業医。じん肺・振動障害・騒音性難聴などの職業性疾病も確認。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'hy-gakko-hoken',
    name: '学校保健',
    subject: 'hygiene',
    examRounds: [30, 33, 34],
    importance: 'B',
    officialLarge: '母子保健・学校保健',
    officialMedium: '学校保健',
    officialSmall: '学校保健統計・出席停止・就学時健康診断',
    normalizedTheme: '学校保健',
    aliases: ['学校感染症', '被患率', '就学時健康診断'],
    relatedThemes: ['hy-boshi-hoken'],
    studyPoint: '学校保健統計調査で中・高生の被患率が高いのは裸眼視力1.0未満（近視）、次いでう歯。学校管理下の死亡は突然死（心臓系）が最多。就学時健康診断の実施主体は市町村教育委員会。学校感染症の種類（第1〜3種）と出席停止期間。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'hy-boshi-hoken',
    name: '母子保健・環境保健',
    subject: 'hygiene',
    examRounds: [29, 31, 34],
    importance: 'B',
    officialLarge: '母子保健・環境保健',
    officialMedium: '母子保健と生活環境',
    officialSmall: '乳児死亡率・周産期死亡率・上水道水質基準・放射線衛生',
    normalizedTheme: '母子保健・環境保健',
    aliases: ['乳児死亡率', '周産期死亡率', '上水道水質基準'],
    relatedThemes: ['hy-ekigaku'],
    studyPoint: '乳児死亡率＝出生1000対1年未満死亡数。周産期死亡率＝出産1000対（妊娠22週以後の死産＋早期新生児死亡）。上水道水質基準で「検出されないこと」と規定されるのは大腸菌。放射線（α線・β線・γ線）の特性と実効線量の単位（Sv）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 関係法規（追加） ────────────────────────────
  t({
    id: 'rg-menkyo',
    name: 'あはき法：免許と名簿',
    subject: 'regulations',
    examRounds: [29, 31, 33, 34],
    importance: 'A',
    officialLarge: '関係法規',
    officialMedium: 'あはき法：免許',
    officialSmall: '免許の付与・名簿登録・書換え・返納・欠格事由',
    normalizedTheme: 'あはき法：免許',
    aliases: ['厚生労働大臣', 'あはき師名簿', '免許証の返納'],
    relatedThemes: ['kanke-hokki', 'rg-seijutsujo'],
    studyPoint: '免許は厚生労働大臣が与え、名簿は厚生労働省が管理。名簿の登録消除事由は死亡・失踪宣告・免許取消（業務停止では消除されない）。本籍地変更は免許証の書換え交付申請。免許取消・業務停止処分では5日以内に免許証を厚生労働大臣に返納。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'rg-seijutsujo',
    name: '施術所の届出と構造設備基準',
    subject: 'regulations',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '関係法規',
    officialMedium: 'あはき法：施術所',
    officialSmall: '開設届・構造設備基準・面積・換気・消毒設備',
    normalizedTheme: 'あはき法：施術所',
    aliases: ['6.6㎡', '待合室3.3㎡', '外気開放'],
    relatedThemes: ['rg-menkyo', 'rg-kokoku'],
    studyPoint: '施術所開設は所在地の都道府県知事に開設後10日以内に届出（専ら出張のみは住所地の知事に届出）。構造設備基準：施術室6.6㎡以上・待合室3.3㎡以上・施術室の外気開放部分は床面積の1/8以上・採光／照明／換気を十分に・消毒設備。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'rg-kokoku',
    name: '施術所の広告規制',
    subject: 'regulations',
    examRounds: [30, 32],
    importance: 'B',
    officialLarge: '関係法規',
    officialMedium: 'あはき法：広告の制限',
    officialSmall: '広告可能事項と誇大広告の禁止',
    normalizedTheme: 'あはき法：広告',
    aliases: ['広告制限', '適応症', '誇大広告'],
    relatedThemes: ['rg-seijutsujo'],
    studyPoint: '広告できるのは施術者の氏名・住所、施術所の名称・電話・所在地、施術日・時間、出張施術の旨、駐車設備など法定事項に限る。「◯◯に効く」等の適応症、技術の優秀性、美容鍼・中国鍼などの名称は広告できない。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'rg-bassoku',
    name: '罰則規定と業務上の義務',
    subject: 'regulations',
    examRounds: [29, 30, 31, 34],
    importance: 'A',
    officialLarge: '関係法規',
    officialMedium: 'あはき法：罰則と義務',
    officialSmall: '無免許業務・守秘義務・消毒義務・虚偽報告の罰則',
    normalizedTheme: 'あはき法：罰則',
    aliases: ['無免許業務', '守秘義務', '消毒義務'],
    relatedThemes: ['rg-menkyo', 'rg-seijutsujo'],
    studyPoint: '最も重いのは無免許業務（1年以下の懲役または50万円以下の罰金）。守秘義務違反も同等。都道府県知事への虚偽報告や広告違反は30万円以下の罰金。はり師には施術に当たり手指・鍼・施術部位の消毒義務があり、違反は罰金対象。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'rg-iryo-kanren',
    name: '医療関係法規（医療法・他職種法・保健所）',
    subject: 'regulations',
    examRounds: [29, 31, 33, 34],
    importance: 'A',
    officialLarge: '関係法規',
    officialMedium: 'その他の関係法規',
    officialSmall: '医療法・地域保健法・精神保健福祉法・高齢者医療確保法',
    normalizedTheme: '医療関係法規',
    aliases: ['医療法', '保健所', '名称独占', '業務独占'],
    relatedThemes: ['kanke-hokki'],
    studyPoint: '保健所は地域保健法に基づき都道府県・政令指定都市・中核市等が設置し、結核・精神保健・感染症・食品衛生を担う。医療安全支援センター・助産所・病院/診療所の定義は医療法。特定健診・特定保健指導は高齢者医療確保法。名称独占と業務独占の職種別区分を整理。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 生理学（追加） ──────────────────────────────
  t({
    id: 'ph-shinkei-seiri',
    name: '神経の生理（膜電位・シナプス・脊髄反射・脳波）',
    subject: 'physiology',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '神経系の機能',
    officialMedium: '神経・シナプス・反射',
    officialSmall: '活動電位・神経伝達物質・伸張反射・脳波・睡眠',
    normalizedTheme: '神経生理',
    aliases: ['伸張反射', '脳波', 'レム睡眠', 'ドパミン'],
    relatedThemes: ['jiritsu-shinkei', 'ph-kinshukushuku'],
    studyPoint: '膝蓋腱反射・アキレス腱反射は単シナプス性の伸張反射で、受容器は筋紡錘、求心路はIa群線維、遠心路はα運動ニューロン。脳波（α波＝安静閉眼、β波＝覚醒注意、θ波＝浅睡眠、δ波＝深睡眠）。レム睡眠は急速眼球運動・骨格筋緊張低下。大脳皮質の機能局在（中心前回＝運動、中心後回＝体性感覚）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ph-kinshukushuku',
    name: '筋の生理・筋収縮のしくみ',
    subject: 'physiology',
    examRounds: [29, 30, 31, 32],
    importance: 'B',
    officialLarge: '運動系の機能',
    officialMedium: '骨格筋の収縮',
    officialSmall: '興奮収縮連関・滑走説・エネルギー代謝',
    normalizedTheme: '筋生理',
    aliases: ['滑走説', 'トロポニン', 'クレアチンリン酸'],
    relatedThemes: ['ph-shinkei-seiri'],
    studyPoint: '筋収縮：筋小胞体からCa²⁺放出→トロポニンCに結合→トロポミオシンが移動→アクチン・ミオシン架橋形成→滑走。ミオシン頭部がアクチンから離れる（弛緩）過程にATPが必要。無酸素性のエネルギー供給はクレアチンリン酸系・解糖系。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ph-junkan-seiri',
    name: '循環の生理（刺激伝導系・血圧調節・血液）',
    subject: 'physiology',
    examRounds: [30, 31, 32, 33, 34],
    importance: 'A',
    officialLarge: '循環系の機能',
    officialMedium: '心臓と血管・血液',
    officialSmall: '刺激伝導系・体循環と肺循環・血漿蛋白・赤血球',
    normalizedTheme: '循環生理',
    aliases: ['洞房結節', 'アルブミン', 'エリスロポエチン'],
    relatedThemes: ['junkan-kino', 'jiritsu-shinkei'],
    studyPoint: '刺激伝導系（洞房結節→房室結節→ヒス束→左右脚→プルキンエ線維）。肺動脈は静脈血、肺静脈は動脈血。肺血圧（収縮期約25mmHg）は体血圧より低い。血漿蛋白は肝臓で合成（アルブミン＝膠質浸透圧、フィブリノゲン＝凝固）。赤血球は無核・寿命約120日、産生刺激はエリスロポエチン（腎）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ph-kokyu-seiri',
    name: '呼吸の生理',
    subject: 'physiology',
    examRounds: [32, 33, 34],
    importance: 'B',
    officialLarge: '呼吸系の機能',
    officialMedium: 'ガス交換と呼吸調節',
    officialSmall: '呼吸中枢・化学受容器・肺気量分画',
    normalizedTheme: '呼吸生理',
    aliases: ['中枢化学受容器', '肺活量', '残気量'],
    relatedThemes: ['ph-junkan-seiri'],
    studyPoint: '呼吸は体液のpH低下（CO₂増加）で促進、O₂分圧低下でも促進。中枢化学受容器（延髄・CO₂／H⁺に反応）と末梢化学受容器（頸動脈小体・大動脈小体・O₂に反応）。肺気量分画（1回換気量・予備吸気量・予備呼気量・残気量）と肺活量（残気量を含まない）。動脈血SpO₂正常値は約97%。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ph-shokaku-seiri',
    name: '消化・吸収の生理',
    subject: 'physiology',
    examRounds: [29, 30, 31, 33, 34],
    importance: 'A',
    officialLarge: '消化・吸収系の機能',
    officialMedium: '消化液の分泌と栄養素の吸収',
    officialSmall: '胃液分泌の3相・消化酵素・小腸と大腸の機能',
    normalizedTheme: '消化生理',
    aliases: ['ガストリン', 'セクレチン', '脳相・胃相・腸相'],
    relatedThemes: ['ph-taion-taisha'],
    studyPoint: '胃液分泌の調節：脳相（迷走神経→ACh）、胃相（ガストリン→塩酸・ペプシン）、腸相（セクレチン・CCK→抑制）。消化酵素の産生（唾液＝アミラーゼ、胃＝ペプシン、膵＝アミラーゼ・リパーゼ・トリプシン）。糖・アミノ酸・脂質の吸収は主に小腸、大腸は水分・電解質の吸収。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ph-naibunpi-seiri',
    name: '内分泌の生理（ホルモンの分類・作用・分泌調節）',
    subject: 'physiology',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '内分泌系の機能',
    officialMedium: 'ホルモンの種類と作用',
    officialSmall: 'ホルモンの化学的分類・受容体・日内リズム・下垂体ホルモン',
    normalizedTheme: '内分泌生理',
    aliases: ['ペプチドホルモン', 'ステロイドホルモン', 'コルチゾール', 'ADH'],
    relatedThemes: ['ph-taion-taisha'],
    studyPoint: 'ホルモンの分類：ペプチド（水溶性・細胞膜受容体：インスリン・GH）、ステロイド（脂溶性・核内受容体：副腎皮質・性ホルモン）、アミン（甲状腺ホルモン・カテコラミン）。コルチゾールは早朝が最高（日内リズム）。ADH（バソプレシン）は視床下部で産生・下垂体後葉から分泌し腎集合管で水再吸収。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ph-taion-taisha',
    name: '体温調節・代謝・栄養素の生理',
    subject: 'physiology',
    examRounds: [29, 30, 32, 34],
    importance: 'A',
    officialLarge: '代謝・体温',
    officialMedium: '体温調節と物質代謝',
    officialSmall: '体温調節中枢・放熱と産熱・ビタミン・糖質代謝',
    normalizedTheme: '代謝・体温生理',
    aliases: ['視床下部', '脂溶性ビタミン', 'グリコーゲン'],
    relatedThemes: ['ph-naibunpi-seiri', 'ph-shokaku-seiri'],
    studyPoint: '体温調節中枢は視床下部。放熱促進は皮膚血管拡張・発汗、産熱促進は甲状腺ホルモン・骨格筋収縮（ふるえ）。脂溶性ビタミン（A・D・E・K）は過剰症あり。糖質は単糖・二糖・多糖に分類され、グリコーゲンは肝・骨格筋に貯蔵。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ph-jin-taieki-meneki',
    name: '腎・体液・免疫の生理',
    subject: 'physiology',
    examRounds: [29, 31, 33, 34],
    importance: 'A',
    officialLarge: '腎・体液・生体防御',
    officialMedium: '腎機能・体液・免疫',
    officialSmall: '糸球体濾過・体液区分・尿の性状・免疫グロブリン・免疫細胞',
    normalizedTheme: '腎・免疫生理',
    aliases: ['糸球体濾過量', '免疫グロブリン', 'IgG', 'IgM'],
    relatedThemes: ['ph-naibunpi-seiri', 'menekigaku'],
    studyPoint: '糸球体濾過量は糸球体血圧の上昇で増加。血液pHは7.4±0.05、成人尿量1〜2L/日、細胞内液は体液の約60%。免疫グロブリン：IgG（最多・胎盤通過・二次応答）、IgM（一次応答で最初に産生・五量体）、IgA（分泌型・粘膜）、IgE（アレルギー）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ph-saibo-idenshi',
    name: '細胞の生理と遺伝子',
    subject: 'physiology',
    examRounds: [29, 31, 32, 33],
    importance: 'B',
    officialLarge: '細胞の機能',
    officialMedium: '細胞小器官と遺伝情報',
    officialSmall: '細胞小器官の機能・核酸・細胞分裂・細胞の寿命',
    normalizedTheme: '細胞生理',
    aliases: ['ミトコンドリア', 'mRNA', '核膜'],
    relatedThemes: ['ph-shinkei-seiri'],
    studyPoint: '細胞小器官の機能（ミトコンドリア＝ATP産生、リボソーム＝蛋白合成、ゴルジ体＝分泌蛋白修飾、リソソーム＝細胞内消化）。DNAは4塩基（A・T・G・C）、RNAはウラシルを含む。細胞分裂時に核膜は消失。神経細胞は基本的に再生しない。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 解剖学（追加） ──────────────────────────────
  t({
    id: 'an-undoki',
    name: '運動器の解剖（骨・関節・筋・靭帯）',
    subject: 'anatomy',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '運動器系',
    officialMedium: '骨格・関節・骨格筋',
    officialSmall: '上肢・下肢・体幹の骨と筋・脊柱の靭帯・横隔膜',
    normalizedTheme: '運動器解剖',
    aliases: ['腕神経叢', '横隔膜の裂孔', '黄色靭帯'],
    relatedThemes: ['an-shinkei', 'kin-kishi-teishi'],
    studyPoint: '横隔膜の3裂孔（大動脈裂孔T12＝大動脈・胸管、食道裂孔T10＝食道・迷走神経、大静脈孔T8＝下大静脈）。下肢の筋の神経支配（大腿四頭筋＝大腿神経、内転筋群＝閉鎖神経、中殿筋＝上殿神経、下腿三頭筋＝脛骨神経）。脊柱管の背側に最も近い靭帯は黄色靭帯。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'an-shinkei',
    name: '神経系の解剖（脳・脳神経・脊髄・伝導路）',
    subject: 'anatomy',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '神経系',
    officialMedium: '中枢神経・末梢神経・自律神経',
    officialSmall: '脳の区分・脳神経12対・感覚伝導路・自律神経節',
    normalizedTheme: '神経解剖',
    aliases: ['脳神経', '脊髄視床路', '後索-内側毛帯路'],
    relatedThemes: ['an-undoki', 'no-shinkei'],
    studyPoint: '間脳＝視床＋視床下部、脳幹＝中脳＋橋＋延髄。延髄に呼吸・心拍・嚥下中枢。温痛覚は脊髄後角で交叉し外側脊髄視床路を上行、深部感覚は後索（薄束・楔状束）→延髄で交叉→内側毛帯。交感神経節前線維は脊髄側角、白交通枝＝有髄の節前線維、灰白交通枝＝無髄の節後線維。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'an-junkanki',
    name: '循環器の解剖（心臓・動脈・静脈）',
    subject: 'anatomy',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'A',
    officialLarge: '循環器系',
    officialMedium: '心臓と脈管',
    officialSmall: '心臓の4腔と弁・冠状動静脈・体表の動脈・門脈系',
    normalizedTheme: '循環器解剖',
    aliases: ['僧帽弁', '冠状静脈洞', '奇静脈', '門脈'],
    relatedThemes: ['an-naizo', 'an-shinkei'],
    studyPoint: '心臓は4腔・4弁（三尖弁＝右房室、僧帽弁〈二尖弁〉＝左房室、大動脈弁・肺動脈弁＝半月弁）。房室弁に腱索あり、半月弁に腱索なし。冠状静脈洞は右心房に注ぐ。上大静脈に直接注ぐのは奇静脈。門脈は腸管→肝臓への静脈系。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'an-naizo',
    name: '内臓の解剖（消化器・呼吸器・泌尿生殖器）',
    subject: 'anatomy',
    examRounds: [29, 30, 31, 32, 34],
    importance: 'A',
    officialLarge: '内臓系',
    officialMedium: '消化器・呼吸器・泌尿生殖器',
    officialSmall: '食道の狭窄・肺葉・小腸と大腸・腎臓とネフロン・生殖器',
    normalizedTheme: '内臓解剖',
    aliases: ['食道の3狭窄', 'ネフロン', 'キーゼルバッハ部位'],
    relatedThemes: ['an-junkanki'],
    studyPoint: '食道の3狭窄（食道入口部・気管分岐/大動脈弓部・横隔膜貫通部）。右肺3葉・左肺2葉。ネフロン＝腎小体（糸球体＋ボウマン嚢）＋尿細管、糸球体は皮質。膵臓は後腹膜臓器で外分泌・内分泌の両機能。受精は卵管膨大部。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'an-naibunpi',
    name: '内分泌器官の解剖',
    subject: 'anatomy',
    examRounds: [33, 34],
    importance: 'B',
    officialLarge: '内分泌系',
    officialMedium: '内分泌腺',
    officialSmall: '下垂体・甲状腺・上皮小体・副腎・膵島',
    normalizedTheme: '内分泌解剖',
    aliases: ['甲状腺濾胞', 'ランゲルハンス島', '上皮小体'],
    relatedThemes: ['ph-naibunpi-seiri', 'an-naizo'],
    studyPoint: '甲状腺は濾胞構造でコロイド（サイログロブリン）を貯蔵、上皮小体は甲状腺の後面。上甲状腺動脈は外頸動脈の枝。膵ランゲルハンス島のα細胞（グルカゴン）・β細胞（インスリン・最多）・δ細胞（ソマトスタチン）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'an-soshiki',
    name: '組織学（上皮・結合組織・細胞間結合・皮膚）',
    subject: 'anatomy',
    examRounds: [30, 33, 34],
    importance: 'B',
    officialLarge: '人体の構成',
    officialMedium: '組織と細胞',
    officialSmall: '上皮組織・皮膚の層構造・細胞間結合・筋組織',
    normalizedTheme: '組織学',
    aliases: ['介在板', 'デスモソーム', 'タイト結合', '表皮の層'],
    relatedThemes: ['an-undoki'],
    studyPoint: '皮膚は表皮（基底層・有棘層・顆粒層・角質層）・真皮・皮下組織の3層。細胞間結合（タイト結合＝物質の透過制限、接着帯、デスモソーム＝機械的結合、ギャップ結合＝電気的連絡）。心筋は介在板（ギャップ結合＋デスモソーム）で連結。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── はり理論（追加） ────────────────────────────
  t({
    id: 'ha-goshin-kozo',
    name: '毫鍼の構造・鍼の種類と規格',
    subject: 'acupuncture-theory',
    examRounds: [30, 32, 33, 34],
    importance: 'A',
    officialLarge: '鍼の基礎',
    officialMedium: '鍼の構造と種類',
    officialSmall: '毫鍼の各部・鍼の規格（番手・寸法）・特殊鍼',
    normalizedTheme: '鍼の構造',
    aliases: ['鍼尖', '鍼体', '鍼根', '鍼柄', '皮内鍼', '円皮鍼'],
    relatedThemes: ['ha-kodai-kyushin', 'hari-shigeki-ryo'],
    studyPoint: '毫鍼の構造は鍼尖・鍼体・鍼根・鍼柄。太さは番手（号数）、長さは寸で表す。鍼尖の形状（松葉型・卵型・スリオロシ型など）と刺入感の違い。皮内鍼・円皮鍼・小児鍼（接触鍼）・鍉鍼などの特殊鍼の適応。毫鍼は管理医療機器に分類される。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ha-shishinho',
    name: '刺鍼の方式と刺法',
    subject: 'acupuncture-theory',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '鍼の操作',
    officialMedium: '刺鍼術式',
    officialSmall: '管鍼法・押手と刺手・単刺術・雀啄術・旋撚術・置鍼術',
    normalizedTheme: '刺鍼術式',
    aliases: ['管鍼法', '押手', '刺手', '雀啄術', '十二刺'],
    relatedThemes: ['ha-goshin-kozo', 'hari-shigeki-ryo'],
    studyPoint: '管鍼法は杉山和一が創案し、鍼管を用いて切皮を容易にする。押手の役割（鍼の支持・固定、痛みの軽減、消毒野の保持、刺入方向の保持）と刺手の役割。刺法の種類（単刺術・雀啄術・旋撚術・振せん術・置鍼術・間歇術）と刺激特性。古典の刺法（十二刺・九刺・五刺）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ha-hosha',
    name: '補瀉手技',
    subject: 'acupuncture-theory',
    examRounds: [29, 31, 33, 34],
    importance: 'A',
    officialLarge: '鍼の操作',
    officialMedium: '補法と瀉法',
    officialSmall: '呼吸補瀉・迎随補瀉・開闔補瀉・徐疾補瀉・捻転補瀉',
    normalizedTheme: '補瀉',
    aliases: ['呼吸補瀉', '迎随補瀉', '開闔補瀉'],
    relatedThemes: ['ha-shishinho', 'ben-sho-ron-chi'],
    studyPoint: '補法は虚証に、瀉法は実証に用いる。呼吸補瀉（補＝呼気時に刺入・吸気時に抜鍼、瀉＝逆）、迎随補瀉（補＝経の流注に随って刺入、瀉＝経に逆らって刺入＝迎える）、開闔補瀉（補＝抜鍼後すぐ按じて閉じる、瀉＝穴を開けたままにする）、徐疾補瀉。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ha-kodai-kyushin',
    name: '古代九鍼',
    subject: 'acupuncture-theory',
    examRounds: [31, 33, 34],
    importance: 'B',
    officialLarge: '鍼の基礎',
    officialMedium: '鍼の歴史',
    officialSmall: '九鍼の名称・形状・用途',
    normalizedTheme: '古代九鍼',
    aliases: ['鑱鍼', '鋒鍼', '鍉鍼', '毫鍼'],
    relatedThemes: ['ha-goshin-kozo'],
    studyPoint: '九鍼（鑱鍼・員鍼・鍉鍼・鋒鍼・鈹鍼・員利鍼・毫鍼・長鍼・大鍼）の形状と用途。鑱鍼＝浅刺・瀉熱、員鍼＝按摩、鍉鍼＝脈を按じる（刺さない）、鋒鍼＝三稜鍼で瀉血、鈹鍼＝排膿、毫鍼＝一般的刺鍼、長鍼＝深部、大鍼＝関節の水を瀉す。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ha-tokki',
    name: '得気（ひびき）と刺鍼反応',
    subject: 'acupuncture-theory',
    examRounds: [29, 31, 32, 34],
    importance: 'A',
    officialLarge: '鍼の作用',
    officialMedium: '刺鍼時の反応',
    officialSmall: '得気の受容器・刺鍼反応（軸索反射・フレア）',
    normalizedTheme: '得気',
    aliases: ['ひびき', '響き', 'ポリモーダル受容器'],
    relatedThemes: ['ha-shishin-seiri', 'ha-tsukaku-dendoro'],
    studyPoint: '得気（ひびき）は刺鍼部の重だるさ・鈍痛・放散感で、深部の受容器（筋・腱・結合組織のポリモーダル受容器や自由神経終末）が関与。刺鍼部の発赤（フレア）は軸索反射でサブスタンスP・CGRPが遊離し血管拡張・血漿漏出を起こす反応。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ha-kansen-taisaku',
    name: '鍼の消毒・感染対策',
    subject: 'acupuncture-theory',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: 'リスク管理',
    officialMedium: '衛生管理と感染対策',
    officialSmall: '滅菌と消毒・CNT・単回使用鍼・医療廃棄物処理',
    normalizedTheme: '感染対策',
    aliases: ['CNT', 'クリーンニードルテクニック', 'ディスポーザブル鍼'],
    relatedThemes: ['hari-risk-kanri', 'hy-kansen-yobo'],
    studyPoint: 'CNT（クリーンニードルテクニック）＝滅菌済み鍼の使用・鍼体に触れない・施術野の消毒・押手指の管理。鍼は高圧蒸気滅菌（オートクレーブ）またはディスポーザブル（単回使用）が原則。使用済み鍼は感染性廃棄物として耐貫通性容器（バイオハザードマーク）で処理。施術者はB型肝炎ワクチン接種が推奨される。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ha-chintsu-kiko',
    name: '鍼鎮痛の機序',
    subject: 'acupuncture-theory',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '鍼の作用機序',
    officialMedium: '鎮痛の神経機構',
    officialSmall: 'ゲートコントロール説・内因性オピオイド・DNIC・下行性疼痛抑制系',
    normalizedTheme: '鍼鎮痛',
    aliases: ['ゲートコントロール説', 'エンドルフィン', 'DNIC', '下行性疼痛抑制系'],
    relatedThemes: ['ha-tsukaku-dendoro', 'ha-hari-tsuden'],
    studyPoint: 'ゲートコントロール説：太い触圧覚線維（Aβ）の入力が脊髄後角で細い侵害線維（C）の伝達を抑制。内因性オピオイド（β-エンドルフィン・エンケファリン・ダイノルフィン）の関与。DNIC（広汎性侵害抑制調節）＝ある部位の侵害刺激が他部位の痛みを抑制。下行性疼痛抑制系（中脳中心灰白質→延髄縫線核→脊髄後角、セロトニン・ノルアドレナリン作動性）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ha-tsukaku-dendoro',
    name: '痛みの受容器と伝導路',
    subject: 'acupuncture-theory',
    examRounds: [30, 31, 33, 34],
    importance: 'A',
    officialLarge: '鍼の作用機序',
    officialMedium: '痛覚の生理',
    officialSmall: '侵害受容器・神経線維の分類・脊髄視床路・痛覚の中枢',
    normalizedTheme: '痛覚生理',
    aliases: ['ポリモーダル受容器', 'Aδ線維', 'C線維', '脊髄視床路'],
    relatedThemes: ['ha-chintsu-kiko', 'ha-tokki'],
    studyPoint: '一次痛（鋭い痛み）はAδ線維（有髄）、二次痛（鈍い痛み）はC線維（無髄）が伝導。ポリモーダル受容器はC線維終末で温度・機械・化学刺激に反応。痛覚は脊髄後角で二次ニューロンに交代し交叉して外側脊髄視床路を上行→視床→大脳皮質体性感覚野。B線維は自律神経節前線維で細い有髄線維。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ha-hari-tsuden',
    name: '低周波鍼通電療法',
    subject: 'acupuncture-theory',
    examRounds: [29, 30, 32, 33],
    importance: 'A',
    officialLarge: '鍼の応用',
    officialMedium: '鍼通電療法',
    officialSmall: '通電の周波数と鎮痛機序・適応・禁忌',
    normalizedTheme: '鍼通電療法',
    aliases: ['EAT', '低周波鍼通電', 'パルス'],
    relatedThemes: ['ha-chintsu-kiko'],
    studyPoint: '低周波鍼通電療法は刺入した鍼を電極として通電する。低頻度（1〜2Hz付近）ではエンケファリン・β-エンドルフィン系、高頻度（100Hz付近）ではダイノルフィン系が関与するとされる。ペースメーカー装着者・体幹前後の心臓を挟む通電は禁忌。適応は疼痛疾患・末梢神経麻痺・筋の機能回復。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ha-shishin-seiri',
    name: '刺鍼の生理作用（軸索反射・自律神経反応・局所血流）',
    subject: 'acupuncture-theory',
    examRounds: [31, 32, 33, 34],
    importance: 'A',
    officialLarge: '鍼の作用機序',
    officialMedium: '生体反応',
    officialSmall: '軸索反射・体性自律神経反射・局所循環改善・免疫応答',
    normalizedTheme: '刺鍼の生理作用',
    aliases: ['軸索反射', '体性内臓反射', 'CGRP'],
    relatedThemes: ['ha-tokki', 'ha-chintsu-kiko'],
    studyPoint: '刺鍼の局所反応：侵害受容器興奮→逆行性伝導→神経ペプチド（サブスタンスP・CGRP）遊離→血管拡張・血漿漏出（軸索反射・フレア現象）。体性自律神経反射（体性感覚入力→自律神経出力の変化＝血圧・胃運動・発汗などの調節）。局所血流増加には内皮由来のNO（一酸化窒素）も関与。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── きゅう理論（追加） ──────────────────────────
  t({
    id: 'ky-mogusa',
    name: '艾（もぐさ）の原料・製造・品質',
    subject: 'moxibustion-theory',
    examRounds: [30, 31, 32, 33, 34],
    importance: 'A',
    officialLarge: '灸の基礎',
    officialMedium: '艾の製造',
    officialSmall: '原料（ヨモギ）・製造工程・精製度と品質',
    normalizedTheme: '艾',
    aliases: ['ヨモギ', '毛茸', 'けんどん', '線香'],
    relatedThemes: ['ky-kyuho-shurui'],
    studyPoint: '艾の原料はヨモギ（艾葉）の葉裏の毛茸・腺毛。製造工程は乾燥→粉砕（石臼で毛茸を分離）→篩い分け→けんどん（夾雑物除去）を繰り返す。高精製の艾は淡黄白色・繊維質が多く・夾雑物と灰分が少なく・燃焼が緩やかで透熱灸（糸状灸）に適する。良質の艾は精油（シネオール等）を多く含む。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ky-kyuho-shurui',
    name: '灸法の種類（有痕灸・無痕灸・隔物灸・灸頭鍼）',
    subject: 'moxibustion-theory',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '灸の操作',
    officialMedium: '施灸法の分類',
    officialSmall: '透熱灸・知熱灸・焦灼灸・打膿灸・隔物灸・温灸・灸頭鍼',
    normalizedTheme: '灸法の種類',
    aliases: ['透熱灸', '知熱灸', '隔物灸', '灸頭鍼', '棒灸'],
    relatedThemes: ['ky-mogusa', 'ky-kinki', 'kyu-fukusayo'],
    studyPoint: '有痕灸（灸痕を残す）：透熱灸（艾炷を燃焼しきる）・焦灼灸（ウオノメ等の組織焼灼）・打膿灸（意図的にⅡ度熱傷をつくり化膿させる）。無痕灸（灸痕を残さない）：知熱灸（熱を感じたら除去）・糸状灸・隔物灸（生姜・にんにく・塩・味噌・附子）・温灸（棒灸・温筒灸）・灸頭鍼。小児には艾条灸（棒灸）が適する。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ky-shigeki-ryo',
    name: '施灸量と刺激の調節',
    subject: 'moxibustion-theory',
    examRounds: [29, 34],
    importance: 'B',
    officialLarge: '灸の操作',
    officialMedium: '刺激量の調節',
    officialSmall: '艾炷の大小・壮数・ひねりの硬さ・施灸間隔',
    normalizedTheme: '施灸量',
    aliases: ['艾炷', '壮数', '半米粒大'],
    relatedThemes: ['ky-kyuho-shurui', 'kyu-fukusayo'],
    studyPoint: '刺激量は艾炷の大きさ（米粒大・半米粒大・糸状）・壮数・ひねりの硬さ・底面の広さ・施灸間隔で調節する。ひねりを硬く・底面を広くすると熱刺激は増大。小児・高齢者・虚弱者・知覚過敏者は小さい艾炷・少ない壮数・柔らかいひねり・艾条灸から始める。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ky-kinki',
    name: '施灸の禁忌・禁灸部位と注意を要する患者',
    subject: 'moxibustion-theory',
    examRounds: [29, 30, 32, 33, 34],
    importance: 'A',
    officialLarge: 'リスク管理',
    officialMedium: '施灸の禁忌',
    officialSmall: '禁灸部位・禁忌状態・易感染性患者への配慮',
    normalizedTheme: '施灸の禁忌',
    aliases: ['禁灸穴', '顔面', '糖尿病'],
    relatedThemes: ['kyu-fukusayo', 'ky-kyuho-shurui'],
    studyPoint: '透熱灸を避ける部位：顔面（特に眼周囲＝睛明・承泣・陽白など）・大血管上・粘膜・関節部・妊婦の腰腹部。禁忌状態：高熱・急性炎症・出血傾向・悪性腫瘍部・皮膚感染部。糖尿病患者は末梢神経障害による知覚低下と創傷治癒遅延から熱傷・感染のリスクが高く、最大限の注意を要する（温灸・隔物灸を選択）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ky-kyokusho-hanno',
    name: '施灸の局所反応（フレア現象・軸索反射）',
    subject: 'moxibustion-theory',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '灸の作用機序',
    officialMedium: '局所の生体反応',
    officialSmall: '侵害受容器の興奮・軸索反射・炎症性物質・熱傷',
    normalizedTheme: '施灸局所反応',
    aliases: ['フレア現象', '軸索反射', 'CGRP', 'ヒスタミン'],
    relatedThemes: ['ky-kyuho-shurui', 'ky-zenshin-sayo'],
    studyPoint: '施灸局所の三徴（発赤・膨隆・熱感）。順序：ポリモーダル受容器の興奮→逆行性（軸索反射）伝導→神経ペプチド（サブスタンスP・CGRP）遊離→血管拡張（フレア）・血漿漏出（浮腫）。施灸初期には肥満細胞からヒスタミンが遊離。透熱灸ではⅡ度熱傷が生じ、炎症性サイトカイン（IL-6等）が産生される。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ky-zenshin-sayo',
    name: '灸の全身作用と作用機序',
    subject: 'moxibustion-theory',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '灸の作用機序',
    officialMedium: '全身反応と神経機構',
    officialSmall: '温熱受容器・熱刺激の伝導路・体性自律神経反射・免疫賦活・HSP',
    normalizedTheme: '灸の全身作用',
    aliases: ['TRPV1', 'B線維', '昇圧反射', 'HSP'],
    relatedThemes: ['ky-kyokusho-hanno', 'ha-shishin-seiri'],
    studyPoint: '温熱刺激はTRPV1受容体（カプサイシン受容体）で受容され、Aδ線維・C線維で伝導し脊髄後角→外側脊髄視床路を上行。施灸→交感神経亢進→血圧上昇（昇圧反射）で、その遠心路は交感神経節前線維（B線維＝細い有髄線維）。施灸は白血球増加・免疫賦活（防衛作用）や熱ショック蛋白質（HSP）誘導にも関与。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'ky-fukusayo-hosoku',
    name: '灸の副作用（熱傷・化膿・灸あたり）と管理',
    subject: 'moxibustion-theory',
    examRounds: [29, 30, 31, 33],
    importance: 'A',
    officialLarge: 'リスク管理',
    officialMedium: '施灸の有害事象',
    officialSmall: '熱傷の深度・灸痕の化膿予防・灸あたり',
    normalizedTheme: '灸の副作用',
    aliases: ['灸あたり', '打膿灸', '熱傷の深度'],
    relatedThemes: ['kyu-fukusayo', 'ky-kinki'],
    studyPoint: '熱傷の深度：Ⅰ度（発赤）・浅達性Ⅱ度（水疱・強い疼痛）・深達性Ⅱ度（水疱・知覚鈍麻）・Ⅲ度（壊死・知覚消失）。打膿灸は意図的なⅡ度熱傷。灸あたり（全身倦怠・疲労・めまい）の予防は刺激量を減らすこと。有痕灸後は灸痕を清潔に保ち、糖尿病・ステロイド長期服用・高齢者は易感染性に注意。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),

  // ── 東洋医学臨床論（追加） ──────────────────────
  t({
    id: 'oc-hakko-bensho',
    name: '八綱弁証（表裏・寒熱・虚実・陰陽）',
    subject: 'oriental-clinical',
    examRounds: [29, 30, 32, 33],
    importance: 'A',
    officialLarge: '弁証論治',
    officialMedium: '八綱弁証',
    officialSmall: '表裏・寒熱・虚実・陰陽の弁別と六経弁証',
    normalizedTheme: '八綱弁証',
    aliases: ['表証', '裏証', '虚実', '少陽病'],
    relatedThemes: ['ben-sho-ron-chi', 'oc-kiketsu-bensho'],
    studyPoint: '八綱弁証の手順はまず表裏（病位）を判断し、次に寒熱・虚実・陰陽へ進む。表証（発病急・悪寒発熱並存・脈浮・発汗法で治療）と裏証（臓腑病・脈沈）。実証（拒按・脈実・実則瀉之）と虚証（喜按・脈虚・虚則補之）。六経弁証の少陽病（往来寒熱・口苦・咽乾・脈弦）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'oc-kiketsu-bensho',
    name: '気血津液弁証',
    subject: 'oriental-clinical',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '弁証論治',
    officialMedium: '気血津液弁証',
    officialSmall: '気虚・気滞・気逆・血虚・血瘀・陰虚・陽虚・痰湿',
    normalizedTheme: '気血津液弁証',
    aliases: ['気虚', '血瘀', '陰虚', '陽虚', '痰湿'],
    relatedThemes: ['oc-hakko-bensho', 'oc-zofu-bensho', 'ki-ketsu-shin-eki'],
    studyPoint: '気虚（倦怠・少気懶言・自汗・活動で悪化・脈虚）、気滞（脹痛・気分で変動）、血虚（顔色萎黄・爪甲蒼白・心悸・月経量少）、血瘀（刺痛〈固定性〉・紫暗舌・渋脈）、陰虚（潮熱・盗汗・五心煩熱・舌紅少苔・脈細数）、陽虚（畏寒肢冷・夜間頻尿・五更泄瀉・舌淡胖・脈沈遅）、痰湿（舌胖大・厚膩苔・滑脈）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'oc-zofu-bensho',
    name: '臓腑弁証',
    subject: 'oriental-clinical',
    examRounds: [29, 30, 31, 32, 33, 34],
    importance: 'S',
    officialLarge: '弁証論治',
    officialMedium: '臓腑弁証',
    officialSmall: '五臓の病証・合病（心腎不交・肝脾不和・心脾両虚）',
    normalizedTheme: '臓腑弁証',
    aliases: ['肝気鬱結', '心腎不交', '肝脾不和', '脾気虚'],
    relatedThemes: ['oc-kiketsu-bensho', 'zo-sho'],
    studyPoint: '肝気鬱結（精神抑鬱・易怒・胸脇脹痛・脈弦→疏肝理気）、心脾両虚（動悸・不眠・健忘＋食欲不振・倦怠→補益心脾）、心腎不交（不眠・動悸・盗汗＝心火亢盛＋腎陰虚）、肝脾不和／肝胃不和（ストレス誘因の胃もたれ・胸やけ・脈弦→疏肝健脾）、腎陽虚（畏寒・腰膝酸軟・五更泄瀉→温補腎陽）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'oc-shinho-shindan',
    name: '四診（脈診・舌診）と証の把握',
    subject: 'oriental-clinical',
    examRounds: [29, 30, 32, 33, 34],
    importance: 'A',
    officialLarge: '弁証論治',
    officialMedium: '四診と診断',
    officialSmall: '望聞問切・脈状・舌質と舌苔',
    normalizedTheme: '四診',
    aliases: ['脈診', '舌診', '浮脈', '弦脈', '滑脈'],
    relatedThemes: ['oc-hakko-bensho', 'oc-kiketsu-bensho'],
    studyPoint: '脈状と証（浮＝表証、沈＝裏証、遅＝寒証、数＝熱証、虚＝虚証、実＝実証、滑＝痰飲・食積・妊娠、渋＝血瘀・血虚、弦＝肝胆病・痛証・痰飲）。舌質（淡＝虚寒、紅＝熱、紫暗＝血瘀）と舌苔（黄＝熱、白＝寒、膩＝痰湿）。四診を統合して八綱→臓腑→気血津液の順に証を絞る。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'oc-keiraku-chiryo',
    name: '経絡治療・配穴法則と経脈病証',
    subject: 'oriental-clinical',
    examRounds: [29, 30, 31, 33],
    importance: 'A',
    officialLarge: '弁証論治',
    officialMedium: '経絡弁証と治療',
    officialSmall: '是動病・所生病・配穴法則・難経六十九難',
    normalizedTheme: '経絡治療',
    aliases: ['是動病', '所生病', '原絡配穴', '兪募配穴', '難経69難'],
    relatedThemes: ['kei-myaku-byo-sho', 'oc-zofu-bensho'],
    studyPoint: '経脈の是動病・所生病から罹患経脈を特定し要穴（原穴・郄穴・絡穴・五兪穴）を選択（循経取穴）。配穴法則：表裏配穴（原絡配穴）、前後配穴（兪募配穴）、上下配穴。難経六十九難「虚すればその母を補い、実すればその子を瀉す」＝五行の相生関係を用いた子母補瀉。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'oc-kakka-chiryo',
    name: '各科疾患・症状別の鍼灸治療',
    subject: 'oriental-clinical',
    examRounds: [29, 30, 32, 34],
    importance: 'A',
    officialLarge: '各種疾患の治療',
    officialMedium: '症状別の弁証と選穴',
    officialSmall: '腰痛・肩こり・頭痛・不眠・月経痛・冷え症・顔面神経麻痺',
    normalizedTheme: '症状別治療',
    aliases: ['腰痛の弁証', '緊張型頭痛', '痺証', '冷え症'],
    relatedThemes: ['oc-kiketsu-bensho', 'oc-keiraku-chiryo'],
    studyPoint: '腰痛の弁証（腎虚＝慢性・腰膝酸軟、血瘀＝刺痛・固定・夜間増悪、寒湿＝冷えで増悪・重だるい）。頭痛（肝陽上亢＝頭頂・後頭部脹痛・弦脈、緊張型＝後頸〜肩の筋緊張〈風池・天柱・肩井・合谷〉）。痺証の行痺・痛痺・着痺・熱痺。冷え症は陽虚型が最多（命門・腎兪・関元に灸）。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
  t({
    id: 'oc-undoki-shinkei',
    name: '運動器・神経疾患の鍼灸治療',
    subject: 'oriental-clinical',
    examRounds: [29, 30],
    importance: 'B',
    officialLarge: '各種疾患の治療',
    officialMedium: '運動器・神経疾患の局所治療',
    officialSmall: '絞扼性神経障害・スポーツ障害・顔面神経麻痺・神経根症',
    normalizedTheme: '運動器・神経疾患治療',
    aliases: ['手根管症候群', 'テニス肘', '顔面神経麻痺', 'デルマトーム'],
    relatedThemes: ['oc-kakka-chiryo', 'cs-shinkeikin'],
    studyPoint: '絞扼性神経障害の治療穴（正中神経＝内関・大陵、尺骨神経＝神門・小海、橈骨神経＝偏歴・陽渓、腓骨神経＝陽陵泉・懸鐘）。スポーツ障害（テニス肘＝曲池・手三里・阿是穴、膝蓋腱炎＝犢鼻・梁丘）。顔面神経麻痺は後遺症期（顔面拘縮・病的共同運動）に強刺激を避ける。神経根症はデルマトームに対応した頸夾脊穴・局所穴を選択。',
    blueprintVersion: '2020',
    questionCountMode: '180',
    sourceReliability: 'indexed_official',
  }),
]

export function getSubject(id: string): Subject | undefined {
  return subjects.find(s => s.id === id)
}

export function getTheme(id: string): Theme | undefined {
  return themes.find(t => t.id === id)
}

export function getThemesBySubject(subjectId: string): Theme[] {
  return themes
    .filter(t => t.subject === subjectId)
    .sort((a, b) => {
      const order = { S: 0, A: 1, B: 2, C: 3 }
      return order[a.importance] - order[b.importance] || b.count - a.count
    })
}
